//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_INDEX_COLOR_INFO
    {
        public DC_INDEX_COLOR_INFO()
        {
            this.DC_PRINT_INFO_INDEX_SETTING = new HashSet<DC_PRINT_INFO_INDEX_SETTING>();
            this.DC_PRINT_INFO_INDEX_SETTING1 = new HashSet<DC_PRINT_INFO_INDEX_SETTING>();
            this.DC_PRINT_INFO_INDEX_SETTING2 = new HashSet<DC_PRINT_INFO_INDEX_SETTING>();
            this.DC_PRINT_INFO_INDEX_SETTING3 = new HashSet<DC_PRINT_INFO_INDEX_SETTING>();
            this.DC_PRINT_INFO_INDEX_SETTING4 = new HashSet<DC_PRINT_INFO_INDEX_SETTING>();
            this.DC_PRINT_INFO_INDEX_SETTING5 = new HashSet<DC_PRINT_INFO_INDEX_SETTING>();
        }
    
        public int SID { get; set; }
        public Nullable<int> JOB_SID { get; set; }
        public string CMYK { get; set; }
        public string RGB { get; set; }
        public string SPCOLOR_NAME { get; set; }
        public Nullable<short> SPCOLOR_DENSITY { get; set; }
        public string COMMENTS { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
    
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_JOB_INFO OM_JOB_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
        public virtual ICollection<DC_PRINT_INFO_INDEX_SETTING> DC_PRINT_INFO_INDEX_SETTING { get; set; }
        public virtual ICollection<DC_PRINT_INFO_INDEX_SETTING> DC_PRINT_INFO_INDEX_SETTING1 { get; set; }
        public virtual ICollection<DC_PRINT_INFO_INDEX_SETTING> DC_PRINT_INFO_INDEX_SETTING2 { get; set; }
        public virtual ICollection<DC_PRINT_INFO_INDEX_SETTING> DC_PRINT_INFO_INDEX_SETTING3 { get; set; }
        public virtual ICollection<DC_PRINT_INFO_INDEX_SETTING> DC_PRINT_INFO_INDEX_SETTING4 { get; set; }
        public virtual ICollection<DC_PRINT_INFO_INDEX_SETTING> DC_PRINT_INFO_INDEX_SETTING5 { get; set; }
    }
}
