//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_INDEX_INFO
    {
        public DC_INDEX_INFO()
        {
            this.DC_INDEX_ADDITIONAL_INFO = new HashSet<DC_INDEX_ADDITIONAL_INFO>();
            this.DC_INDEX_ADDITIONAL_PRINT_INFO = new HashSet<DC_INDEX_ADDITIONAL_PRINT_INFO>();
            this.DC_INDEX_SYN_SETTING = new HashSet<DC_INDEX_SYN_SETTING>();
            this.DC_INDEX_SYN_SETTING1 = new HashSet<DC_INDEX_SYN_SETTING>();
            this.DC_INDEX_INFO1 = new HashSet<DC_INDEX_INFO>();
            this.DC_PRINT_INFO_BG_SETTING = new HashSet<DC_PRINT_INFO_BG_SETTING>();
            this.DC_PRINT_INFO_PAGE_NUM_SETTING = new HashSet<DC_PRINT_INFO_PAGE_NUM_SETTING>();
            this.DC_STYLE_INFO = new HashSet<DC_STYLE_INFO>();
            this.DC_SUBMIT_FILECHECK_RESULT = new HashSet<DC_SUBMIT_FILECHECK_RESULT>();
            this.ID_INDESIGN_REFLECT_STAT = new HashSet<ID_INDESIGN_REFLECT_STAT>();
            this.LK_BLUE_LINK_SUBSCRIBE = new HashSet<LK_BLUE_LINK_SUBSCRIBE>();
            this.LK_ORANGE_LINK_SUBSCRIBE = new HashSet<LK_ORANGE_LINK_SUBSCRIBE>();
            this.LK_RED_LINK_SOURCE_ENTRY = new HashSet<LK_RED_LINK_SOURCE_ENTRY>();
            this.LK_RED_LINK_SUBSCRIBE = new HashSet<LK_RED_LINK_SUBSCRIBE>();
        }
    
        public int SID { get; set; }
        public int DOC_SID { get; set; }
        public string TITLE { get; set; }
        public short INDEX_TYPE { get; set; }
        public Nullable<short> AUDIT_TYPE { get; set; }
        public Nullable<int> PARENT_INDEX_SID { get; set; }
        public short DISPLAY_ORDER { get; set; }
        public short DISPLAY_LEVEL { get; set; }
        public short FILE_DIV_FLAG { get; set; }
        public short OUTPUT_FLAG { get; set; }
        public short ACCOMPANIMENT_FLAG { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public short SERIES_FS_ROOT_FLAG { get; set; }
        public string EDINET_SEQ_CODE { get; set; }
        public short BLANK_ROW_FLAG { get; set; }
        public short INDEXNUM_FLAG { get; set; }
        public short LENTICULARBRACKETS_FLAG { get; set; }
        public short UNUSED_INDEX_FLAG { get; set; }
    
        public virtual ICollection<DC_INDEX_ADDITIONAL_INFO> DC_INDEX_ADDITIONAL_INFO { get; set; }
        public virtual ICollection<DC_INDEX_ADDITIONAL_PRINT_INFO> DC_INDEX_ADDITIONAL_PRINT_INFO { get; set; }
        public virtual ICollection<DC_INDEX_SYN_SETTING> DC_INDEX_SYN_SETTING { get; set; }
        public virtual ICollection<DC_INDEX_SYN_SETTING> DC_INDEX_SYN_SETTING1 { get; set; }
        public virtual ICollection<DC_INDEX_INFO> DC_INDEX_INFO1 { get; set; }
        public virtual DC_INDEX_INFO DC_INDEX_INFO2 { get; set; }
        public virtual OM_DOCUMENT_INFO OM_DOCUMENT_INFO { get; set; }
        public virtual ICollection<DC_PRINT_INFO_BG_SETTING> DC_PRINT_INFO_BG_SETTING { get; set; }
        public virtual ICollection<DC_PRINT_INFO_PAGE_NUM_SETTING> DC_PRINT_INFO_PAGE_NUM_SETTING { get; set; }
        public virtual ICollection<DC_STYLE_INFO> DC_STYLE_INFO { get; set; }
        public virtual ICollection<DC_SUBMIT_FILECHECK_RESULT> DC_SUBMIT_FILECHECK_RESULT { get; set; }
        public virtual ICollection<ID_INDESIGN_REFLECT_STAT> ID_INDESIGN_REFLECT_STAT { get; set; }
        public virtual ICollection<LK_BLUE_LINK_SUBSCRIBE> LK_BLUE_LINK_SUBSCRIBE { get; set; }
        public virtual ICollection<LK_ORANGE_LINK_SUBSCRIBE> LK_ORANGE_LINK_SUBSCRIBE { get; set; }
        public virtual ICollection<LK_RED_LINK_SOURCE_ENTRY> LK_RED_LINK_SOURCE_ENTRY { get; set; }
        public virtual ICollection<LK_RED_LINK_SUBSCRIBE> LK_RED_LINK_SUBSCRIBE { get; set; }
    }
}
