//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_PRINT_INFO_PAGE_BG_SETTING
    {
        public int SID { get; set; }
        public int JOB_SID { get; set; }
        public short PAGE_NUM { get; set; }
        public Nullable<int> IMAGE_SID { get; set; }
        public Nullable<int> COLOR_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
    
        public virtual DC_COLOR_INFO DC_COLOR_INFO { get; set; }
        public virtual DC_PRINT_INFO_BG_IMAGE_INFO DC_PRINT_INFO_BG_IMAGE_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_JOB_INFO OM_JOB_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
    }
}
