//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_PRINT_INFO_INDEX_SETTING
    {
        public int SID { get; set; }
        public int JOB_SID { get; set; }
        public short INDEX_PATTERN_ID { get; set; }
        public short INDEX_WIDTH { get; set; }
        public decimal INDEX_POSITION_TOP { get; set; }
        public decimal INDEX_FONT_SIZE { get; set; }
        public int INDEX_FONT_SID { get; set; }
        public short FONT_HORIZONTAL_POSITION { get; set; }
        public short FONT_VERTICAL_POSITION { get; set; }
        public Nullable<int> MAIN_INDEX_LINE_COLOR_SID { get; set; }
        public Nullable<int> MAIN_INDEX_BACK_COLOR_SID { get; set; }
        public Nullable<int> MAIN_INDEX_FONT_COLOR_SID { get; set; }
        public short MAIN_INDEX_BACK_GRADATION { get; set; }
        public Nullable<int> SUB_INDEX_LINE_COLOR_SID { get; set; }
        public Nullable<int> SUB_INDEX_BACK_COLOR_SID { get; set; }
        public Nullable<int> SUB_INDEX_FONT_COLOR_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
    
        public virtual DC_INDEX_COLOR_INFO DC_INDEX_COLOR_INFO { get; set; }
        public virtual DC_INDEX_COLOR_INFO DC_INDEX_COLOR_INFO1 { get; set; }
        public virtual DC_INDEX_COLOR_INFO DC_INDEX_COLOR_INFO2 { get; set; }
        public virtual DC_INDEX_COLOR_INFO DC_INDEX_COLOR_INFO3 { get; set; }
        public virtual DC_INDEX_COLOR_INFO DC_INDEX_COLOR_INFO4 { get; set; }
        public virtual DC_INDEX_COLOR_INFO DC_INDEX_COLOR_INFO5 { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_FONT_INFO_MASTER OM_FONT_INFO_MASTER { get; set; }
        public virtual OM_JOB_INFO OM_JOB_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
    }
}
