//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_POINT_MARK
    {
        public int SID { get; set; }
        public int JOB_SID { get; set; }
        public string PART_NAME { get; set; }
        public string ELEMENT_NAME { get; set; }
        public string CONTEXT { get; set; }
        public string ORIGINAL_VALUE { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public string FRONTLOADED_VALUE { get; set; }
        public string CURRENT_VALUE { get; set; }
        public short WORD_MARKING_FLAG { get; set; }
        public short FDS_MARKING_FLAG { get; set; }
        public string BRANCH { get; set; }
        public string FORMAT { get; set; }
    
        public virtual OM_JOB_INFO OM_JOB_INFO { get; set; }
    }
}
