//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_SUBMIT_FILE_INFO
    {
        public DC_SUBMIT_FILE_INFO()
        {
            this.DC_SUBMIT_FILE_DATA = new HashSet<DC_SUBMIT_FILE_DATA>();
        }
    
        public long SID { get; set; }
        public int ORDER_SID { get; set; }
        public int CREATE_USER_SID { get; set; }
        public Nullable<short> DISPLAY_ORDER { get; set; }
        public string SUBMIT_TYPE { get; set; }
        public string FILE_NAME { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
    
        public virtual ICollection<DC_SUBMIT_FILE_DATA> DC_SUBMIT_FILE_DATA { get; set; }
        public virtual OM_ORDER_INFO OM_ORDER_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
    }
}
