//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_STYLE_INFO
    {
        public long SID { get; set; }
        public int INDEX_SID { get; set; }
        public byte[] STYLE_DATA { get; set; }
    
        public virtual DC_INDEX_INFO DC_INDEX_INFO { get; set; }
    }
}
