//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWD_KANRYU_DATA
    {
        public int SID { get; set; }
        public string FILE_TYPE { get; set; }
        public string KANRYU_DATE { get; set; }
        public byte[] KANRYU_DATA { get; set; }
        public short STATUS { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    }
}
