//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWD_STP_DATA
    {
        public FWD_STP_DATA()
        {
            this.FWD_FINANCIAL_STATUS = new HashSet<FWD_FINANCIAL_STATUS>();
            this.FWD_FINANCIAL_STATUS1 = new HashSet<FWD_FINANCIAL_STATUS>();
            this.FWD_FINANCIAL_STATUS2 = new HashSet<FWD_FINANCIAL_STATUS>();
            this.FWD_FINANCIAL_STATUS3 = new HashSet<FWD_FINANCIAL_STATUS>();
            this.FWD_RINPOU_STATUS = new HashSet<FWD_RINPOU_STATUS>();
        }
    
        public int SID { get; set; }
        public short RECEIVE_TYPE { get; set; }
        public System.DateTime RECEIVE_DATE { get; set; }
        public string FILE_NAME { get; set; }
        public byte[] FILE_DATA { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        public virtual ICollection<FWD_FINANCIAL_STATUS> FWD_FINANCIAL_STATUS { get; set; }
        public virtual ICollection<FWD_FINANCIAL_STATUS> FWD_FINANCIAL_STATUS1 { get; set; }
        public virtual ICollection<FWD_FINANCIAL_STATUS> FWD_FINANCIAL_STATUS2 { get; set; }
        public virtual ICollection<FWD_FINANCIAL_STATUS> FWD_FINANCIAL_STATUS3 { get; set; }
        public virtual ICollection<FWD_RINPOU_STATUS> FWD_RINPOU_STATUS { get; set; }
    }
}
