//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWD_REPORT_SCHEDULE
    {
        public FWD_REPORT_SCHEDULE()
        {
            this.FWD_FINANCIAL_STATUS = new HashSet<FWD_FINANCIAL_STATUS>();
            this.FWD_RINPOU_STATUS = new HashSet<FWD_RINPOU_STATUS>();
        }
    
        public int SID { get; set; }
        public string DOCUMENT_DIVISION { get; set; }
        public string SUBMISSION_REASON { get; set; }
        public System.DateTime SUBMIT_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public string EDINET_FUND_CODE { get; set; }
        public string EDINET_FUND_NAME { get; set; }
        public Nullable<System.DateTime> PROSPECTUS_START_DATE { get; set; }
        public Nullable<System.DateTime> PROSPECTUS_END_DATE { get; set; }
        public string PERIOD { get; set; }
        public System.DateTime FISCAL_DATE { get; set; }
        public Nullable<System.DateTime> BASIC_DATE { get; set; }
        public Nullable<System.DateTime> AUDIT_DATE { get; set; }
        public Nullable<System.DateTime> PROSPECTUS_DELIVERY_DATE { get; set; }
        public string FUND_CODE { get; set; }
        public string FUND_NAME { get; set; }
        public string MOTHER_FUND_CODE { get; set; }
        public string MOTHER_FUND_NAME { get; set; }
        public string SCHEDULE_STATUS { get; set; }
        public string TEAM_DIVISION { get; set; }
        public Nullable<System.DateTime> PERIOD_START { get; set; }
    
        public virtual ICollection<FWD_FINANCIAL_STATUS> FWD_FINANCIAL_STATUS { get; set; }
        public virtual ICollection<FWD_RINPOU_STATUS> FWD_RINPOU_STATUS { get; set; }
    }
}
