//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWD_SCHEDULE_STATUS
    {
        public int SID { get; set; }
        public System.DateTime RECEIVE_MONTH { get; set; }
        public short STP_REPORT_SCHEDULE_STATUS { get; set; }
        public short STP_AUDIT_SCHEDULE_STATUS { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    }
}
