//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWD_STP_SNAPSHOT
    {
        public int SID { get; set; }
        public int ORDER_SID { get; set; }
        public string INDEX_TITLE { get; set; }
        public string INDEX_EDINET_SEQ_CODE { get; set; }
        public byte[] DOCUMENT_DATA { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        public virtual OM_ORDER_INFO OM_ORDER_INFO { get; set; }
    }
}
