//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_INDESIGN_IMG_DATA
    {
        public int SID { get; set; }
        public int INDESIGN_IMG_SID { get; set; }
        public byte[] IMG_DATA { get; set; }
    
        public virtual ID_INDESIGN_IMG ID_INDESIGN_IMG { get; set; }
    }
}
