//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_INDESIGN_PDF_DATA
    {
        public int SID { get; set; }
        public int INDESIGN_FILE_SID { get; set; }
        public short PDF_TYPE { get; set; }
        public byte[] PDF_DATA { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public short PDF_STAT { get; set; }
    
        public virtual ID_INDESIGN_FILE ID_INDESIGN_FILE { get; set; }
    }
}
