//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_PERFORMANCE_DATA
    {
        public ID_PERFORMANCE_DATA()
        {
            this.ID_PERFORMANCE_QUEUE = new HashSet<ID_PERFORMANCE_QUEUE>();
        }
    
        public int SID { get; set; }
        public int FUND_SID { get; set; }
        public string FILE_NAME { get; set; }
        public byte[] FILE_DATA { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    
        public virtual OM_FUND_INFO OM_FUND_INFO { get; set; }
        public virtual ICollection<ID_PERFORMANCE_QUEUE> ID_PERFORMANCE_QUEUE { get; set; }
    }
}
