//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_PERFORMANCE_QUEUE
    {
        public int SID { get; set; }
        public int DATA_SID { get; set; }
        public string FUND_CODE { get; set; }
        public System.DateTime FISCAL_DATE { get; set; }
        public short STATUS { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    
        public virtual ID_PERFORMANCE_DATA ID_PERFORMANCE_DATA { get; set; }
    }
}
