//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_PARTS_IMAGE_SETTING
    {
        public int SID { get; set; }
        public int INDESIGN_SID { get; set; }
        public string IMAGE_NAME { get; set; }
        public short PAGE_NUM { get; set; }
        public int RESOLUTION { get; set; }
        public string QUALITY { get; set; }
        public string COLOR { get; set; }
        public int SIZE_H { get; set; }
        public int SIZE_W { get; set; }
        public int POSITION_X { get; set; }
        public int POSITION_Y { get; set; }
        public Nullable<System.DateTime> LAST_DOWNLOAD_DATE { get; set; }
    
        public virtual ID_INDESIGN_FILE ID_INDESIGN_FILE { get; set; }
    }
}
