//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_APPLICABLE_DATE
    {
        public int SID { get; set; }
        public int ORDER_GROUP_SID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public int REVISION { get; set; }
        public long TRACKING_ID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        public virtual OM_ORDER_GROUP OM_ORDER_GROUP { get; set; }
    }
}
