//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_BLUE_LINK_SOURCE_ENTRY
    {
        public int SID { get; set; }
        public int DURATION_SID { get; set; }
        public int PATTERN_SID { get; set; }
        public string DATA { get; set; }
        public int REVISION { get; set; }
        public long TRACKING_ID { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        public virtual LK_BLUE_LINK_DURATION LK_BLUE_LINK_DURATION { get; set; }
        public virtual LK_BLUE_LINK_PATTERN LK_BLUE_LINK_PATTERN { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
    }
}
