//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_BLUE_LINK_SUBSCRIBE
    {
        public int SID { get; set; }
        public int INDEX_SID { get; set; }
        public Nullable<int> DURATION_SID { get; set; }
        public int LINK_SID { get; set; }
        public int PATTERN_SID { get; set; }
        public long SOURCE_TRACKING_ID { get; set; }
        public long DURATION_TRACKING_ID { get; set; }
        public Nullable<long> RELATION_TRACKING_ID { get; set; }
        public long APPLICABLE_DATE_TRACKING_ID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int DISCONNECT_STATUS_SID { get; set; }
    
        public virtual DC_INDEX_INFO DC_INDEX_INFO { get; set; }
        public virtual LK_BLUE_LINK_DISCONNECT_STATUS LK_BLUE_LINK_DISCONNECT_STATUS { get; set; }
        public virtual LK_BLUE_LINK_DURATION LK_BLUE_LINK_DURATION { get; set; }
        public virtual LK_BLUE_LINK_ITEM LK_BLUE_LINK_ITEM { get; set; }
        public virtual LK_BLUE_LINK_PATTERN LK_BLUE_LINK_PATTERN { get; set; }
    }
}
