//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_ORANGE_LINK_SOURCE_PUBLISH
    {
        public int SID { get; set; }
        public int ORDER_GROUP_SID { get; set; }
        public int LINK_SID { get; set; }
        public long TRACKING_ID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public int ENTRY_USER_SID { get; set; }
    
        public virtual LK_ORANGE_LINK_ITEM LK_ORANGE_LINK_ITEM { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_ORDER_GROUP OM_ORDER_GROUP { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
    }
}
