//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_ORANGE_LINK_ITEM
    {
        public LK_ORANGE_LINK_ITEM()
        {
            this.LK_ORANGE_LINK_DISCONNECT_STAT = new HashSet<LK_ORANGE_LINK_DISCONNECT_STAT>();
            this.LK_ORANGE_LINK_SOURCE_ENTRY = new HashSet<LK_ORANGE_LINK_SOURCE_ENTRY>();
            this.LK_ORANGE_LINK_SOURCE_PUBLISH = new HashSet<LK_ORANGE_LINK_SOURCE_PUBLISH>();
            this.LK_ORANGE_LINK_SUBSCRIBE = new HashSet<LK_ORANGE_LINK_SUBSCRIBE>();
        }
    
        public int SID { get; set; }
        public int COMPANY_SID { get; set; }
        public string ELEMENT_ID { get; set; }
        public string NAME { get; set; }
        public string DISPLAY_DOC_FORM_ID { get; set; }
        public short DATE_TYPE { get; set; }
        public string PRIMARY_FORMAT { get; set; }
        public string SECONDARY_FORMAT { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        public virtual ICollection<LK_ORANGE_LINK_DISCONNECT_STAT> LK_ORANGE_LINK_DISCONNECT_STAT { get; set; }
        public virtual OM_COMPANY_INFO OM_COMPANY_INFO { get; set; }
        public virtual ICollection<LK_ORANGE_LINK_SOURCE_ENTRY> LK_ORANGE_LINK_SOURCE_ENTRY { get; set; }
        public virtual ICollection<LK_ORANGE_LINK_SOURCE_PUBLISH> LK_ORANGE_LINK_SOURCE_PUBLISH { get; set; }
        public virtual ICollection<LK_ORANGE_LINK_SUBSCRIBE> LK_ORANGE_LINK_SUBSCRIBE { get; set; }
    }
}
