//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_RED_LINK_TARGET_INDEX
    {
        public LK_RED_LINK_TARGET_INDEX()
        {
            this.LK_RED_LINK_BRANCH = new HashSet<LK_RED_LINK_BRANCH>();
            this.LK_RED_LINK_RELATION = new HashSet<LK_RED_LINK_RELATION>();
            this.LK_RED_LINK_SUBSCRIBE = new HashSet<LK_RED_LINK_SUBSCRIBE>();
        }
    
        public int SID { get; set; }
        public int COMPANY_SID { get; set; }
        public int DOC_FORM_ID { get; set; }
        public string ELEMENT_ID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public string NAME { get; set; }
        public short HIERARCHY_HEADING_FLAG { get; set; }
    
        public virtual ICollection<LK_RED_LINK_BRANCH> LK_RED_LINK_BRANCH { get; set; }
        public virtual ICollection<LK_RED_LINK_RELATION> LK_RED_LINK_RELATION { get; set; }
        public virtual ICollection<LK_RED_LINK_SUBSCRIBE> LK_RED_LINK_SUBSCRIBE { get; set; }
        public virtual OM_COMPANY_INFO OM_COMPANY_INFO { get; set; }
    }
}
