//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_RED_LINK_SUBSCRIBE
    {
        public int SID { get; set; }
        public int INDEX_SID { get; set; }
        public int TARGET_SID { get; set; }
        public Nullable<int> PERIOD_SID { get; set; }
        public int PATTERN_SID { get; set; }
        public long SOURCE_TRACKING_ID { get; set; }
        public long APPLICABLE_DATE_TRACKING_ID { get; set; }
        public short DISCONNECT_STATUS { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public long PERIOD_TRACKING_ID { get; set; }
    
        public virtual DC_INDEX_INFO DC_INDEX_INFO { get; set; }
        public virtual LK_RED_LINK_PATTERN LK_RED_LINK_PATTERN { get; set; }
        public virtual LK_RED_LINK_PERIOD LK_RED_LINK_PERIOD { get; set; }
        public virtual LK_RED_LINK_TARGET_INDEX LK_RED_LINK_TARGET_INDEX { get; set; }
    }
}
