//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_RED_LINK_SOURCE_IMAGE_INFO
    {
        public int SID { get; set; }
        public int SOURCE_ENTRY_SID { get; set; }
        public int IMAGE_INFO_SID { get; set; }
        public string FILE_NAME { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        public virtual DC_IMAGE_INFO DC_IMAGE_INFO { get; set; }
        public virtual LK_RED_LINK_SOURCE_ENTRY LK_RED_LINK_SOURCE_ENTRY { get; set; }
    }
}
