//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_RED_LINK_PERIOD
    {
        public LK_RED_LINK_PERIOD()
        {
            this.LK_RED_LINK_PERIOD_ENTRY = new HashSet<LK_RED_LINK_PERIOD_ENTRY>();
            this.LK_RED_LINK_PERIOD_PUBLISH = new HashSet<LK_RED_LINK_PERIOD_PUBLISH>();
            this.LK_RED_LINK_SOURCE_ENTRY = new HashSet<LK_RED_LINK_SOURCE_ENTRY>();
            this.LK_RED_LINK_SOURCE_PUBLISH = new HashSet<LK_RED_LINK_SOURCE_PUBLISH>();
            this.LK_RED_LINK_SUBSCRIBE = new HashSet<LK_RED_LINK_SUBSCRIBE>();
        }
    
        public int SID { get; set; }
        public int PATTERN_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public Nullable<long> DELETED_TRACKING_ID { get; set; }
    
        public virtual LK_RED_LINK_PATTERN LK_RED_LINK_PATTERN { get; set; }
        public virtual ICollection<LK_RED_LINK_PERIOD_ENTRY> LK_RED_LINK_PERIOD_ENTRY { get; set; }
        public virtual ICollection<LK_RED_LINK_PERIOD_PUBLISH> LK_RED_LINK_PERIOD_PUBLISH { get; set; }
        public virtual ICollection<LK_RED_LINK_SOURCE_ENTRY> LK_RED_LINK_SOURCE_ENTRY { get; set; }
        public virtual ICollection<LK_RED_LINK_SOURCE_PUBLISH> LK_RED_LINK_SOURCE_PUBLISH { get; set; }
        public virtual ICollection<LK_RED_LINK_SUBSCRIBE> LK_RED_LINK_SUBSCRIBE { get; set; }
    }
}
