//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_AUTO_GRP_JOB_REF
    {
        public int SID { get; set; }
        public int AUTO_GRP_SID { get; set; }
        public int SELECT_JOB_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
    
        public virtual OM_JOB_INFO OM_JOB_INFO { get; set; }
        public virtual OM_AUTO_GRP_MST OM_AUTO_GRP_MST { get; set; }
    }
}
