//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ATTACH_DOC_REVISION_INFO
    {
        public OM_ATTACH_DOC_REVISION_INFO()
        {
            this.OM_ATTACH_DOC_FILE_INFO = new HashSet<OM_ATTACH_DOC_FILE_INFO>();
            this.OM_ORDER_ATTACH_INFO = new HashSet<OM_ORDER_ATTACH_INFO>();
        }
    
        public int SID { get; set; }
        public int ATTACH_DOC_SID { get; set; }
        public Nullable<System.DateTime> APPLICATION_START_DATE { get; set; }
        public Nullable<System.DateTime> APPLICATION_END_DATE { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
    
        public virtual ICollection<OM_ATTACH_DOC_FILE_INFO> OM_ATTACH_DOC_FILE_INFO { get; set; }
        public virtual OM_ATTACH_DOC_INFO OM_ATTACH_DOC_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
        public virtual ICollection<OM_ORDER_ATTACH_INFO> OM_ORDER_ATTACH_INFO { get; set; }
    }
}
