//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ATTACH_DOC_INFO
    {
        public OM_ATTACH_DOC_INFO()
        {
            this.OM_AGREEMENT_RELATION = new HashSet<OM_AGREEMENT_RELATION>();
            this.OM_ATTACH_DOC_REVISION_INFO = new HashSet<OM_ATTACH_DOC_REVISION_INFO>();
        }
    
        public int SID { get; set; }
        public string NAME_ID { get; set; }
        public string CONTENTS_TYPE { get; set; }
        public int COMPANY_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
    
        public virtual ICollection<OM_AGREEMENT_RELATION> OM_AGREEMENT_RELATION { get; set; }
        public virtual ICollection<OM_ATTACH_DOC_REVISION_INFO> OM_ATTACH_DOC_REVISION_INFO { get; set; }
        public virtual OM_COMPANY_INFO OM_COMPANY_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
    }
}
