//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_COMPANY_ADDITIONAL_INFO
    {
        public int SID { get; set; }
        public int COMPANY_SID { get; set; }
        public Nullable<short> ACCOUNTING_STANDARDS { get; set; }
        public Nullable<System.DateTime> FISCAL_DATE { get; set; }
        public Nullable<short> CONSOLIDATION_STATUS { get; set; }
        public string CONNECTION_IP { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public string FINANCIAL_CODE { get; set; }
        public short CONTLINK_EXECTYPE { get; set; }
        public byte[] USER_EVENT_LIST { get; set; }
        public string TEISEI_FONT_FAMILY { get; set; }
        public byte[] WORD_MARKING { get; set; }
        public Nullable<int> MARKING_ITEM_LIST_SID { get; set; }
        public short OUTPUT_FLAG_EXECTYPE { get; set; }
        public short DELETE_DATA_TODO_MANAGEMENT { get; set; }
        public short DELETE_DATA_TODO_FINANCIAL { get; set; }
        public short DELETE_DATA_YUHO { get; set; }
        public short DELETE_DATA_HANKI { get; set; }
        public short RINPO_USED_TAXONOMY_FLAG { get; set; }
        public short TEISEI_DISPLAY_ORDER_KEY { get; set; }
        public short EDIT_HISTORY_FLAG { get; set; }
        public short TEISEI_PARTIAL_RECREATE_FLAG { get; set; }
        public short SYNC_YUHO_HANKI_EXECTYPE { get; set; }
        public short AUTO_GROUP_FLAG { get; set; }
        public short BULK_PROOFREADING_FLAG { get; set; }
    
        public virtual OM_COMPANY_INFO OM_COMPANY_INFO { get; set; }
        public virtual OM_MARKING_ITEM_LIST OM_MARKING_ITEM_LIST { get; set; }
    }
}
