//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_JOB_INFO
    {
        public OM_JOB_INFO()
        {
            this.DC_COLOR_INFO = new HashSet<DC_COLOR_INFO>();
            this.DC_DOCUMENT_HISTORY = new HashSet<DC_DOCUMENT_HISTORY>();
            this.DC_DOCUMENT_HISTORY_COPY_INFO = new HashSet<DC_DOCUMENT_HISTORY_COPY_INFO>();
            this.DC_FONT_INFO = new HashSet<DC_FONT_INFO>();
            this.DC_IMAGE_INFO = new HashSet<DC_IMAGE_INFO>();
            this.DC_INDEX_COLOR_INFO = new HashSet<DC_INDEX_COLOR_INFO>();
            this.DC_INDEX_STYLE = new HashSet<DC_INDEX_STYLE>();
            this.DC_INDEX_SYN_SETTING = new HashSet<DC_INDEX_SYN_SETTING>();
            this.DC_INDEX_SYN_SETTING1 = new HashSet<DC_INDEX_SYN_SETTING>();
            this.DC_POINT_MARK = new HashSet<DC_POINT_MARK>();
            this.DC_PRINT_INFO_BG_IMAGE_INFO = new HashSet<DC_PRINT_INFO_BG_IMAGE_INFO>();
            this.DC_PRINT_INFO_DETAIL = new HashSet<DC_PRINT_INFO_DETAIL>();
            this.DC_PRINT_INFO_HEAD = new HashSet<DC_PRINT_INFO_HEAD>();
            this.DC_PRINT_INFO_INDEX_SETTING = new HashSet<DC_PRINT_INFO_INDEX_SETTING>();
            this.DC_PRINT_INFO_PAGE_BG_SETTING = new HashSet<DC_PRINT_INFO_PAGE_BG_SETTING>();
            this.OM_AUTO_GRP_JOB_REF = new HashSet<OM_AUTO_GRP_JOB_REF>();
            this.OM_CUST_GRP_JOB_REF = new HashSet<OM_CUST_GRP_JOB_REF>();
            this.OM_DOCUMENT_ACCESS_INFO = new HashSet<OM_DOCUMENT_ACCESS_INFO>();
            this.OM_DOCUMENT_INFO = new HashSet<OM_DOCUMENT_INFO>();
            this.OM_JOB_FORM_INFO = new HashSet<OM_JOB_FORM_INFO>();
            this.OM_SELECT_GRP_AND_JOB = new HashSet<OM_SELECT_GRP_AND_JOB>();
            this.XB_BASIC_INFO = new HashSet<XB_BASIC_INFO>();
            this.OM_REVISION_INFO = new HashSet<OM_REVISION_INFO>();
            this.OM_SELECT_GRP_AND_JOB1 = new HashSet<OM_SELECT_GRP_AND_JOB>();
        }
    
        public int SID { get; set; }
        public int ORDER_SID { get; set; }
        public string JOB_TYPE { get; set; }
        public int REVISION_NUMBER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
    
        public virtual ICollection<DC_COLOR_INFO> DC_COLOR_INFO { get; set; }
        public virtual ICollection<DC_DOCUMENT_HISTORY> DC_DOCUMENT_HISTORY { get; set; }
        public virtual ICollection<DC_DOCUMENT_HISTORY_COPY_INFO> DC_DOCUMENT_HISTORY_COPY_INFO { get; set; }
        public virtual ICollection<DC_FONT_INFO> DC_FONT_INFO { get; set; }
        public virtual ICollection<DC_IMAGE_INFO> DC_IMAGE_INFO { get; set; }
        public virtual ICollection<DC_INDEX_COLOR_INFO> DC_INDEX_COLOR_INFO { get; set; }
        public virtual ICollection<DC_INDEX_STYLE> DC_INDEX_STYLE { get; set; }
        public virtual ICollection<DC_INDEX_SYN_SETTING> DC_INDEX_SYN_SETTING { get; set; }
        public virtual ICollection<DC_INDEX_SYN_SETTING> DC_INDEX_SYN_SETTING1 { get; set; }
        public virtual ICollection<DC_POINT_MARK> DC_POINT_MARK { get; set; }
        public virtual ICollection<DC_PRINT_INFO_BG_IMAGE_INFO> DC_PRINT_INFO_BG_IMAGE_INFO { get; set; }
        public virtual ICollection<DC_PRINT_INFO_DETAIL> DC_PRINT_INFO_DETAIL { get; set; }
        public virtual ICollection<DC_PRINT_INFO_HEAD> DC_PRINT_INFO_HEAD { get; set; }
        public virtual ICollection<DC_PRINT_INFO_INDEX_SETTING> DC_PRINT_INFO_INDEX_SETTING { get; set; }
        public virtual ICollection<DC_PRINT_INFO_PAGE_BG_SETTING> DC_PRINT_INFO_PAGE_BG_SETTING { get; set; }
        public virtual ICollection<OM_AUTO_GRP_JOB_REF> OM_AUTO_GRP_JOB_REF { get; set; }
        public virtual ICollection<OM_CUST_GRP_JOB_REF> OM_CUST_GRP_JOB_REF { get; set; }
        public virtual ICollection<OM_DOCUMENT_ACCESS_INFO> OM_DOCUMENT_ACCESS_INFO { get; set; }
        public virtual ICollection<OM_DOCUMENT_INFO> OM_DOCUMENT_INFO { get; set; }
        public virtual ICollection<OM_JOB_FORM_INFO> OM_JOB_FORM_INFO { get; set; }
        public virtual ICollection<OM_SELECT_GRP_AND_JOB> OM_SELECT_GRP_AND_JOB { get; set; }
        public virtual OM_ORDER_INFO OM_ORDER_INFO { get; set; }
        public virtual ICollection<XB_BASIC_INFO> XB_BASIC_INFO { get; set; }
        public virtual ICollection<OM_REVISION_INFO> OM_REVISION_INFO { get; set; }
        public virtual ICollection<OM_SELECT_GRP_AND_JOB> OM_SELECT_GRP_AND_JOB1 { get; set; }
    }
}
