//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_MESSAGE_DATA
    {
        public int SID { get; set; }
        public int MESSAGE_SID { get; set; }
        public byte[] FILE_DATA { get; set; }
    
        public virtual OM_MESSAGE_INFO OM_MESSAGE_INFO { get; set; }
    }
}
