//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_MST_GRP_MST
    {
        public OM_MST_GRP_MST()
        {
            this.OM_MST_GRP_FUND_REF = new HashSet<OM_MST_GRP_FUND_REF>();
        }
    
        public int SID { get; set; }
        public string GRP_NAME { get; set; }
        public int COMPANY_SID { get; set; }
        public short GRP_TYPE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
    
        public virtual OM_COMPANY_INFO OM_COMPANY_INFO { get; set; }
        public virtual ICollection<OM_MST_GRP_FUND_REF> OM_MST_GRP_FUND_REF { get; set; }
    }
}
