//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_MESSAGE_INFO
    {
        public OM_MESSAGE_INFO()
        {
            this.OM_MESSAGE_DATA = new HashSet<OM_MESSAGE_DATA>();
        }
    
        public int SID { get; set; }
        public short MESSAGE_TYPE { get; set; }
        public string TITLE { get; set; }
        public string FILE_NAME { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
    
        public virtual ICollection<OM_MESSAGE_DATA> OM_MESSAGE_DATA { get; set; }
    }
}
