//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ORDER_GROUP
    {
        public OM_ORDER_GROUP()
        {
            this.LK_APPLICABLE_DATE = new HashSet<LK_APPLICABLE_DATE>();
            this.LK_APPLICABLE_DATE_PUBLISH = new HashSet<LK_APPLICABLE_DATE_PUBLISH>();
            this.LK_BLUE_LINK_DISCONNECT_STATUS = new HashSet<LK_BLUE_LINK_DISCONNECT_STATUS>();
            this.LK_ORANGE_LINK_DISCONNECT_STAT = new HashSet<LK_ORANGE_LINK_DISCONNECT_STAT>();
            this.LK_ORANGE_LINK_SOURCE_ENTRY = new HashSet<LK_ORANGE_LINK_SOURCE_ENTRY>();
            this.LK_ORANGE_LINK_SOURCE_PUBLISH = new HashSet<LK_ORANGE_LINK_SOURCE_PUBLISH>();
            this.LK_RED_LINK_RELATION = new HashSet<LK_RED_LINK_RELATION>();
            this.OM_FINANCIAL_SCHEDULE_INFO = new HashSet<OM_FINANCIAL_SCHEDULE_INFO>();
            this.OM_ORDER_INFO = new HashSet<OM_ORDER_INFO>();
        }
    
        public int SID { get; set; }
        public short GROUP_TYPE { get; set; }
        public Nullable<int> FUND_SID { get; set; }
        public Nullable<System.DateTime> FISCAL_DATE { get; set; }
        public Nullable<System.DateTime> DISCLOSURE_SUBMIT_DATE { get; set; }
        public Nullable<System.DateTime> SUBSCRIPTION_SUBMIT_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_USER_SID { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<int> ENTRY_USER_SID { get; set; }
        public string PERIOD_NAME { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public short TODOKEDE_FLAG { get; set; }
        public short TEITODO_FLAG { get; set; }
        public short YUHO_FLAG { get; set; }
        public short HANKI_FLAG { get; set; }
        public short SEIKYU_FLAG { get; set; }
        public short KOUFU_FLAG { get; set; }
        public short RINPO_FLAG { get; set; }
        public short MINASHI_FLAG { get; set; }
        public short DISCONNECT_FLAG { get; set; }
    
        public virtual ICollection<LK_APPLICABLE_DATE> LK_APPLICABLE_DATE { get; set; }
        public virtual ICollection<LK_APPLICABLE_DATE_PUBLISH> LK_APPLICABLE_DATE_PUBLISH { get; set; }
        public virtual ICollection<LK_BLUE_LINK_DISCONNECT_STATUS> LK_BLUE_LINK_DISCONNECT_STATUS { get; set; }
        public virtual ICollection<LK_ORANGE_LINK_DISCONNECT_STAT> LK_ORANGE_LINK_DISCONNECT_STAT { get; set; }
        public virtual ICollection<LK_ORANGE_LINK_SOURCE_ENTRY> LK_ORANGE_LINK_SOURCE_ENTRY { get; set; }
        public virtual ICollection<LK_ORANGE_LINK_SOURCE_PUBLISH> LK_ORANGE_LINK_SOURCE_PUBLISH { get; set; }
        public virtual ICollection<LK_RED_LINK_RELATION> LK_RED_LINK_RELATION { get; set; }
        public virtual ICollection<OM_FINANCIAL_SCHEDULE_INFO> OM_FINANCIAL_SCHEDULE_INFO { get; set; }
        public virtual OM_FUND_INFO OM_FUND_INFO { get; set; }
        public virtual ICollection<OM_ORDER_INFO> OM_ORDER_INFO { get; set; }
    }
}
