//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ORDER_INFO
    {
        public OM_ORDER_INFO()
        {
            this.DC_SEARCH_CHARACTER = new HashSet<DC_SEARCH_CHARACTER>();
            this.DC_SUBMIT_FILE_INFO = new HashSet<DC_SUBMIT_FILE_INFO>();
            this.DC_SUBMIT_FILE_INIT_SETTING = new HashSet<DC_SUBMIT_FILE_INIT_SETTING>();
            this.DC_SUBMIT_FILECHECK_RESULT = new HashSet<DC_SUBMIT_FILECHECK_RESULT>();
            this.FWD_FINANCIAL_STATUS = new HashSet<FWD_FINANCIAL_STATUS>();
            this.FWD_KANRYU_FUND_INFO = new HashSet<FWD_KANRYU_FUND_INFO>();
            this.FWD_RINPOU_STATUS = new HashSet<FWD_RINPOU_STATUS>();
            this.FWD_STP_SNAPSHOT = new HashSet<FWD_STP_SNAPSHOT>();
            this.FWD_SUBMIT_INFO = new HashSet<FWD_SUBMIT_INFO>();
            this.ID_INDESIGN_COLOR_INFO = new HashSet<ID_INDESIGN_COLOR_INFO>();
            this.ID_INDESIGN_FILE = new HashSet<ID_INDESIGN_FILE>();
            this.ID_INDESIGN_FONT_INFO = new HashSet<ID_INDESIGN_FONT_INFO>();
            this.ID_WORKLOG_INFO = new HashSet<ID_WORKLOG_INFO>();
            this.OM_DOCUMENT_BASE_INFO = new HashSet<OM_DOCUMENT_BASE_INFO>();
            this.OM_JOB_INFO = new HashSet<OM_JOB_INFO>();
            this.OM_ORDER_ACCESS_INFO = new HashSet<OM_ORDER_ACCESS_INFO>();
            this.OM_ORDER_ACCESS_USER_INFO = new HashSet<OM_ORDER_ACCESS_USER_INFO>();
            this.OM_ORDER_ADDITIONAL_INFO = new HashSet<OM_ORDER_ADDITIONAL_INFO>();
            this.OM_ORDER_ATTACH_INFO = new HashSet<OM_ORDER_ATTACH_INFO>();
            this.OM_PDF_INFO = new HashSet<OM_PDF_INFO>();
            this.OM_README_INFO = new HashSet<OM_README_INFO>();
            this.OM_RELATION_ORDER = new HashSet<OM_RELATION_ORDER>();
            this.OM_RELATION_ORDER1 = new HashSet<OM_RELATION_ORDER>();
            this.OM_SCENARIO_CHANGE_LOG = new HashSet<OM_SCENARIO_CHANGE_LOG>();
            this.OM_TEISEI_OPTION_INFO = new HashSet<OM_TEISEI_OPTION_INFO>();
        }
    
        public int SID { get; set; }
        public string ORDER_CODE { get; set; }
        public int COMPANY_SID { get; set; }
        public string EDINET_CODE { get; set; }
        public Nullable<System.DateTime> FISCAL_DATE { get; set; }
        public short CONSOLIDATION_STATUS { get; set; }
        public short DOC_ACCESS_CONTROL_FLAG { get; set; }
        public string DESCRIPTION { get; set; }
        public string USER_COMMENT { get; set; }
        public int PHASE_SCENARIO_ID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public Nullable<int> FUND_SID { get; set; }
        public Nullable<int> ORDER_GROUP_SID { get; set; }
        public short SERIES_FS_COUNT { get; set; }
        public Nullable<System.DateTime> INTERIM_FISCAL_DATE { get; set; }
        public short FINANCE_INSPECTION_ALLOW { get; set; }
        public short MINASHI_FLAG { get; set; }
        public short BOUND_VOLUME_TYPE { get; set; }
        public short AUDIT_INSERT_TYPE { get; set; }
        public short YAKKAN_SHARE_FLAG { get; set; }
        public string EDINET_SUBMIT_ID { get; set; }
        public Nullable<System.DateTime> EDINET_SUBMIT_DATE { get; set; }
        public byte[] RINPO_USED_TAXONOMY { get; set; }
        public string PAST_ORDER_CODE { get; set; }
        public short NX_MIGRATED_FLAG { get; set; }
        public short INVALID_SUBMIT_DATE_CHECK_FLAG { get; set; }
    
        public virtual ICollection<DC_SEARCH_CHARACTER> DC_SEARCH_CHARACTER { get; set; }
        public virtual ICollection<DC_SUBMIT_FILE_INFO> DC_SUBMIT_FILE_INFO { get; set; }
        public virtual ICollection<DC_SUBMIT_FILE_INIT_SETTING> DC_SUBMIT_FILE_INIT_SETTING { get; set; }
        public virtual ICollection<DC_SUBMIT_FILECHECK_RESULT> DC_SUBMIT_FILECHECK_RESULT { get; set; }
        public virtual ICollection<FWD_FINANCIAL_STATUS> FWD_FINANCIAL_STATUS { get; set; }
        public virtual ICollection<FWD_KANRYU_FUND_INFO> FWD_KANRYU_FUND_INFO { get; set; }
        public virtual ICollection<FWD_RINPOU_STATUS> FWD_RINPOU_STATUS { get; set; }
        public virtual ICollection<FWD_STP_SNAPSHOT> FWD_STP_SNAPSHOT { get; set; }
        public virtual ICollection<FWD_SUBMIT_INFO> FWD_SUBMIT_INFO { get; set; }
        public virtual ICollection<ID_INDESIGN_COLOR_INFO> ID_INDESIGN_COLOR_INFO { get; set; }
        public virtual ICollection<ID_INDESIGN_FILE> ID_INDESIGN_FILE { get; set; }
        public virtual ICollection<ID_INDESIGN_FONT_INFO> ID_INDESIGN_FONT_INFO { get; set; }
        public virtual ICollection<ID_WORKLOG_INFO> ID_WORKLOG_INFO { get; set; }
        public virtual OM_COMPANY_INFO OM_COMPANY_INFO { get; set; }
        public virtual ICollection<OM_DOCUMENT_BASE_INFO> OM_DOCUMENT_BASE_INFO { get; set; }
        public virtual OM_FUND_INFO OM_FUND_INFO { get; set; }
        public virtual ICollection<OM_JOB_INFO> OM_JOB_INFO { get; set; }
        public virtual ICollection<OM_ORDER_ACCESS_INFO> OM_ORDER_ACCESS_INFO { get; set; }
        public virtual ICollection<OM_ORDER_ACCESS_USER_INFO> OM_ORDER_ACCESS_USER_INFO { get; set; }
        public virtual ICollection<OM_ORDER_ADDITIONAL_INFO> OM_ORDER_ADDITIONAL_INFO { get; set; }
        public virtual ICollection<OM_ORDER_ATTACH_INFO> OM_ORDER_ATTACH_INFO { get; set; }
        public virtual OM_ORDER_GROUP OM_ORDER_GROUP { get; set; }
        public virtual ICollection<OM_PDF_INFO> OM_PDF_INFO { get; set; }
        public virtual ICollection<OM_README_INFO> OM_README_INFO { get; set; }
        public virtual ICollection<OM_RELATION_ORDER> OM_RELATION_ORDER { get; set; }
        public virtual ICollection<OM_RELATION_ORDER> OM_RELATION_ORDER1 { get; set; }
        public virtual ICollection<OM_SCENARIO_CHANGE_LOG> OM_SCENARIO_CHANGE_LOG { get; set; }
        public virtual ICollection<OM_TEISEI_OPTION_INFO> OM_TEISEI_OPTION_INFO { get; set; }
    }
}
