//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_OPTION_CONTRACT_INFO
    {
        public int SID { get; set; }
        public int COMPANY_ID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public Nullable<int> TYPE_FLAG { get; set; }
        public byte[] BASIC_DATA_VALUE { get; set; }
        public short WEB_IMAGE_FLAG { get; set; }
        public short XML_OUTPUT_FLAG { get; set; }
        public short SEIMOKU_PDF_FLAG { get; set; }
        public short ATTACH_DOC_FLAG { get; set; }
        public short YAKKAN_SHARE_FLAG { get; set; }
        public short KOUFU_HP_PDF_FLAG { get; set; }
        public short WEB_LINEARIZE { get; set; }
        public short FAIMSWD_FLAG { get; set; }
        public short INTEGRATION_REPORT_FLAG { get; set; }
        public short TEISEI_SUBMIT_FILE_FLAG { get; set; }
        public short DOCUMENT_TITLE_SETTING_FLAG { get; set; }
        public short SUBMIT_FILE_NAME_FLAG { get; set; }
        public short THREE_COLOR_LINK_FLAG { get; set; }
        public short TEXT_SEARCH_FLAG { get; set; }
    
        public virtual OM_COMPANY_INFO OM_COMPANY_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
    }
}
