//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_PDF_INFO
    {
        public OM_PDF_INFO()
        {
            this.OM_PDF_FILE_COUPLING = new HashSet<OM_PDF_FILE_COUPLING>();
            this.OM_PDF_PAGE_SETTING = new HashSet<OM_PDF_PAGE_SETTING>();
        }
    
        public int SID { get; set; }
        public int ORDER_SID { get; set; }
        public short PAGE_NUMBER_FLAG { get; set; }
        public short PAGE_NUMBER_HIGE_FLAG { get; set; }
        public string PAGE_NUMBER_HIGE_CHAR { get; set; }
        public short PAGE_NUMBER_FONT_ID { get; set; }
        public decimal PAGE_NUMBER_FONT_SIZE { get; set; }
        public short BOOKMARK_SETTING_FLAG { get; set; }
        public short DOCUMENT_BRACKETS_FLAG { get; set; }
        public short OPEN_DISPLAY { get; set; }
        public short OPEN_PAGE_LAYOUT { get; set; }
        public short OPEN_MAGNIFICATION { get; set; }
        public string OVERVIEW_TITLE { get; set; }
        public string OVERVIEW_AUTHOR { get; set; }
        public string OVERVIEW_SUBTITLE { get; set; }
        public string OVERVIEW_KEYWORD { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public Nullable<System.DateTime> FILLING_DATE { get; set; }
    
        public virtual OM_ORDER_INFO OM_ORDER_INFO { get; set; }
        public virtual ICollection<OM_PDF_FILE_COUPLING> OM_PDF_FILE_COUPLING { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
        public virtual ICollection<OM_PDF_PAGE_SETTING> OM_PDF_PAGE_SETTING { get; set; }
    }
}
