//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_README_DATA
    {
        public int SID { get; set; }
        public int README_SID { get; set; }
        public byte[] README_DATA { get; set; }
    
        public virtual OM_README_INFO OM_README_INFO { get; set; }
    }
}
