//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_REV_ORG_MAPPING
    {
        public OM_REV_ORG_MAPPING()
        {
            this.OM_APPROVAL_INFO = new HashSet<OM_APPROVAL_INFO>();
        }
    
        public int SID { get; set; }
        public int REVISION_SID { get; set; }
        public int REV_DOC_SID { get; set; }
        public int ORG_DOC_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
    
        public virtual ICollection<OM_APPROVAL_INFO> OM_APPROVAL_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_REVISION_INFO OM_REVISION_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
    }
}
