//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_RELATION_FUND
    {
        public int SID { get; set; }
        public int FUND_SID { get; set; }
        public int RELATION_FUND_SID { get; set; }
    
        public virtual OM_FUND_INFO OM_FUND_INFO { get; set; }
        public virtual OM_FUND_INFO OM_FUND_INFO1 { get; set; }
    }
}
