//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class XB_BASIC_INFO
    {
        public XB_BASIC_INFO()
        {
            this.XB_FS_INFO = new HashSet<XB_FS_INFO>();
            this.XB_SERIES_FS_INFO = new HashSet<XB_SERIES_FS_INFO>();
            this.XB_TAXONOMY_DATA = new HashSet<XB_TAXONOMY_DATA>();
            this.XB_STR_ITEM = new HashSet<XB_STR_ITEM>();
            this.XB_ENTITY = new HashSet<XB_ENTITY>();
            this.XB_EXPLICIT_MEMBER = new HashSet<XB_EXPLICIT_MEMBER>();
            this.XB_PERIOD = new HashSet<XB_PERIOD>();
        }
    
        public int SID { get; set; }
        public int JOB_SID { get; set; }
        public string EDINET_SEQ_CODE { get; set; }
        public string FINANCIAL_CODE { get; set; }
        public System.DateTime FISCAL_DATE { get; set; }
        public Nullable<System.DateTime> FISCAL_END_DATE { get; set; }
        public short CONSOLIDATION_STATUS { get; set; }
        public Nullable<short> CON_ACCOUNT_STANDARD_CODE { get; set; }
        public Nullable<short> NONCON_ACCOUNT_STANDARD_CODE { get; set; }
        public Nullable<System.DateTime> CON_TAXONOMY_RELEASE_DATE { get; set; }
        public Nullable<System.DateTime> NONCON_TAXONOMY_RELEASE_DATE { get; set; }
        public Nullable<int> CON_MONETARY_ITEM_DECIMALS { get; set; }
        public Nullable<int> NONCON_MONETARY_ITEM_DECIMALS { get; set; }
        public Nullable<int> CON_MONETARY_ITEM_ROUNDING { get; set; }
        public Nullable<int> NONCON_MONETARY_ITEM_ROUNDING { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime SUBMISSION_DATE { get; set; }
        public short SUBMISSION_COUNT { get; set; }
    
        public virtual OM_JOB_INFO OM_JOB_INFO { get; set; }
        public virtual ICollection<XB_FS_INFO> XB_FS_INFO { get; set; }
        public virtual ICollection<XB_SERIES_FS_INFO> XB_SERIES_FS_INFO { get; set; }
        public virtual ICollection<XB_TAXONOMY_DATA> XB_TAXONOMY_DATA { get; set; }
        public virtual ICollection<XB_STR_ITEM> XB_STR_ITEM { get; set; }
        public virtual ICollection<XB_ENTITY> XB_ENTITY { get; set; }
        public virtual ICollection<XB_EXPLICIT_MEMBER> XB_EXPLICIT_MEMBER { get; set; }
        public virtual ICollection<XB_PERIOD> XB_PERIOD { get; set; }
    }
}
