//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class XB_CONTEXT
    {
        public XB_CONTEXT()
        {
            this.XB_SCENARIO = new HashSet<XB_SCENARIO>();
        }
    
        public long SID { get; set; }
        public int DOC_SID { get; set; }
        public string CONTEXT_ID { get; set; }
        public string ENTITY_SCHEME_NAME_SPACE { get; set; }
        public string ENTITY_ID { get; set; }
        public Nullable<System.DateTime> PERIOD_START_DATE { get; set; }
        public Nullable<System.DateTime> PERIOD_END_DATE { get; set; }
        public Nullable<System.DateTime> PERIOD_INSTANT { get; set; }
        public string LABEL { get; set; }
    
        public virtual OM_DOCUMENT_INFO OM_DOCUMENT_INFO { get; set; }
        public virtual ICollection<XB_SCENARIO> XB_SCENARIO { get; set; }
    }
}
