//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class XB_FOOTNOTE_STR_ITEM
    {
        public int SID { get; set; }
        public int FOOTNOTE_SID { get; set; }
        public long STR_ITEM_SID { get; set; }
        public string FOOTNOTE_LINKROLE { get; set; }
        public string FOOTNOTE_ROLE { get; set; }
    
        public virtual XB_FOOTNOTE XB_FOOTNOTE { get; set; }
        public virtual XB_STR_ITEM XB_STR_ITEM { get; set; }
    }
}
