//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class XB_MEDURE
    {
        public XB_MEDURE()
        {
            this.XB_UNIT_DENOMINATOR_MEDURE = new HashSet<XB_UNIT_DENOMINATOR_MEDURE>();
            this.XB_UNIT_NUMERATOR_MEDURE = new HashSet<XB_UNIT_NUMERATOR_MEDURE>();
        }
    
        public int SID { get; set; }
        public int DOC_SID { get; set; }
        public string PREFIX { get; set; }
        public string NAMESPACE { get; set; }
        public string ID { get; set; }
        public string LABEL { get; set; }
    
        public virtual OM_DOCUMENT_INFO OM_DOCUMENT_INFO { get; set; }
        public virtual ICollection<XB_UNIT_DENOMINATOR_MEDURE> XB_UNIT_DENOMINATOR_MEDURE { get; set; }
        public virtual ICollection<XB_UNIT_NUMERATOR_MEDURE> XB_UNIT_NUMERATOR_MEDURE { get; set; }
    }
}
