//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class XB_SERIES_FS_INFO
    {
        public int SID { get; set; }
        public int BASIC_SID { get; set; }
        public string EDINET_SEQ_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_USER_SID { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<int> ENTRY_USER_SID { get; set; }
    
        public virtual XB_BASIC_INFO XB_BASIC_INFO { get; set; }
    }
}
