//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class XB_UNIT_DENOMINATOR_MEDURE
    {
        public int SID { get; set; }
        public int UNIT_SID { get; set; }
        public int MEDURE_SID { get; set; }
    
        public virtual XB_MEDURE XB_MEDURE { get; set; }
        public virtual XB_UNIT XB_UNIT { get; set; }
    }
}
