//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_DOCUMENT_HISTORY_COPY_DATA
    {
        public int SID { get; set; }
        public int HISTORY_COPY_SID { get; set; }
        public byte[] SNAPSHOT_DATA { get; set; }
        public System.DateTime DATA_UPDATE_DATE { get; set; }
        public int DATA_UPDATE_USER_SID { get; set; }
        public bool USER_TYPE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public bool INVISIBLE { get; set; }
        public bool FIXED_FLAG { get; set; }
    
        public virtual DC_DOCUMENT_HISTORY_COPY_INFO DC_DOCUMENT_HISTORY_COPY_INFO { get; set; }
    }
}
