//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_IMAGE_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DC_IMAGE_INFO()
        {
            this.LK_RED_LINK_SOURCE_IMAGE_INFO = new HashSet<LK_RED_LINK_SOURCE_IMAGE_INFO>();
        }
    
        public int SID { get; set; }
        public int JOB_SID { get; set; }
        public int CONTENTS_HIGH_SID { get; set; }
        public Nullable<int> WIDTH_HIGH { get; set; }
        public Nullable<int> HEIGHT_HIGH { get; set; }
        public Nullable<int> CONTENTS_LOW_SID { get; set; }
        public Nullable<int> WIDTH_LOW { get; set; }
        public Nullable<int> HEIGHT_LOW { get; set; }
        public Nullable<int> RESOLUTION { get; set; }
        public byte[] THUMBNAIL { get; set; }
        public string COMMENTS { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_EXT { get; set; }
        public long FILE_SIZE { get; set; }
        public string FILE_EXT_LOW { get; set; }
        public Nullable<int> CONTENTS_SOURCE_SID { get; set; }
        public string SOURCE_EXT { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
    
        public virtual DC_IMAGE_DATA DC_IMAGE_DATA { get; set; }
        public virtual DC_IMAGE_DATA DC_IMAGE_DATA1 { get; set; }
        public virtual DC_IMAGE_DATA DC_IMAGE_DATA2 { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_JOB_INFO OM_JOB_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_SOURCE_IMAGE_INFO> LK_RED_LINK_SOURCE_IMAGE_INFO { get; set; }
    }
}
