//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_PRINT_INFO_HEAD
    {
        public int SID { get; set; }
        public int JOB_SID { get; set; }
        public string PAPER_SIZE { get; set; }
        public byte BODY_SIZE_HEIGHT { get; set; }
        public byte BODY_SIZE_WIDTH { get; set; }
        public decimal BASIC_FONT_SIZE { get; set; }
        public decimal COLUMN_COUNT_PER_PAGE { get; set; }
        public decimal LINE_PITCH { get; set; }
        public decimal LINE_COUNT_PER_PAGE { get; set; }
        public int BASIC_FONT_SID { get; set; }
        public decimal BASIC_TABLE_FONT_SIZE { get; set; }
        public int PAGE_NUMBER_FONT_SID { get; set; }
        public decimal PAGE_NUMBER_FONT_SIZE { get; set; }
        public int PAGE_NUMBER_FONT_COLOR_SID { get; set; }
        public bool PAGE_NUMBER_LOCATION { get; set; }
        public bool PAGE_NUMBER_CHAR_TYPE { get; set; }
        public string PAGE_NUMBER_SET { get; set; }
        public decimal PAGE_NUMBER_POSITION_BOTTOM { get; set; }
        public decimal PAGE_NUMBER_POSITION_OUTSIDE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public int BASIC_FONT_COLOR_SID { get; set; }
        public Nullable<bool> AUTO_INDEX_SETTING { get; set; }
        public bool BODY_MARGIN_TYPE { get; set; }
    
        public virtual DC_COLOR_INFO DC_COLOR_INFO { get; set; }
        public virtual DC_COLOR_INFO DC_COLOR_INFO1 { get; set; }
        public virtual OM_FONT_INFO_MASTER OM_FONT_INFO_MASTER { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_JOB_INFO OM_JOB_INFO { get; set; }
        public virtual OM_FONT_INFO_MASTER OM_FONT_INFO_MASTER1 { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
    }
}
