//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_PRINT_INFO_PAGE_NUM_SETTING
    {
        public int SID { get; set; }
        public int INDEX_SID { get; set; }
        public bool PAGE_NUMBER_VIEW_FLAG { get; set; }
        public byte INITIAL_PAGE_NUMBER { get; set; }
        public bool AUTO_PAGE_NUMBER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
    
        public virtual DC_INDEX_INFO DC_INDEX_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
    }
}
