//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_MAIL_INFO_CC
    {
        public int SID { get; set; }
        public int FL_MAIL_INFO_SID { get; set; }
        public Nullable<int> OM_USER_INFO_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
    
        public virtual FL_MAIL_INFO FL_MAIL_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
    }
}
