//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_USER_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FL_USER_INFO()
        {
            this.FL_USER_INFO1 = new HashSet<FL_USER_INFO>();
        }
    
        public int SID { get; set; }
        public int OM_USER_INFO_SID { get; set; }
        public Nullable<int> FL_COMPANY_RELATION_SID { get; set; }
        public bool INVALIDATED { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
    
        public virtual FL_COMPANY_RELATION FL_COMPANY_RELATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FL_USER_INFO> FL_USER_INFO1 { get; set; }
        public virtual FL_USER_INFO FL_USER_INFO2 { get; set; }
    }
}
