//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWD_SUBMIT_DATA
    {
        public int SID { get; set; }
        public int SUBMIT_INFO_SID { get; set; }
        public byte[] FILE_DATA { get; set; }
        public bool SUBMIT_FILE_FLAG { get; set; }
    
        public virtual FWD_SUBMIT_INFO FWD_SUBMIT_INFO { get; set; }
    }
}
