//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWD_KANRYU_SCHEDULE
    {
        public int SID { get; set; }
        public int FINANCIAL_STATUS_SID { get; set; }
        public System.DateTime KANRYU_DATE { get; set; }
        public bool COOPETATION_FLAG { get; set; }
        public bool CORRECTION_FLAG { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        public virtual FWD_FINANCIAL_STATUS FWD_FINANCIAL_STATUS { get; set; }
    }
}
