//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWD_STP_DATA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FWD_STP_DATA()
        {
            this.FWD_FINANCIAL_STATUS = new HashSet<FWD_FINANCIAL_STATUS>();
            this.FWD_FINANCIAL_STATUS1 = new HashSet<FWD_FINANCIAL_STATUS>();
            this.FWD_FINANCIAL_STATUS2 = new HashSet<FWD_FINANCIAL_STATUS>();
            this.FWD_FINANCIAL_STATUS3 = new HashSet<FWD_FINANCIAL_STATUS>();
            this.FWD_RINPOU_STATUS = new HashSet<FWD_RINPOU_STATUS>();
        }
    
        public int SID { get; set; }
        public bool RECEIVE_TYPE { get; set; }
        public System.DateTime RECEIVE_DATE { get; set; }
        public string FILE_NAME { get; set; }
        public byte[] FILE_DATA { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWD_FINANCIAL_STATUS> FWD_FINANCIAL_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWD_FINANCIAL_STATUS> FWD_FINANCIAL_STATUS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWD_FINANCIAL_STATUS> FWD_FINANCIAL_STATUS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWD_FINANCIAL_STATUS> FWD_FINANCIAL_STATUS3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWD_RINPOU_STATUS> FWD_RINPOU_STATUS { get; set; }
    }
}
