//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_GRAPH_INFO
    {
        public int SID { get; set; }
        public int INDESIGN_IMG_SID { get; set; }
        public byte[] APPEARANCE_INFO { get; set; }
        public byte[] DISPLAY_INFO { get; set; }
        public byte[] INPUT_INFO { get; set; }
        public byte[] RANGE_INFO { get; set; }
    
        public virtual ID_INDESIGN_IMG ID_INDESIGN_IMG { get; set; }
    }
}
