//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_INDESIGN_BGPOUR_QUEUE
    {
        public int SID { get; set; }
        public string NODE_NAME { get; set; }
        public int ORDER_SID { get; set; }
        public int JOB_SID { get; set; }
        public byte TIME_OUT { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public bool STATUS_FLAG { get; set; }
        public bool DEMAND_PROCESS_TYPE { get; set; }
        public string INDD_APP_VER { get; set; }
    }
}
