//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_INDESIGN_REFLECT_STAT
    {
        public int SID { get; set; }
        public int DOC_SID { get; set; }
        public int INDEX_SID { get; set; }
        public int ORDER_SID { get; set; }
        public int JOB_SID { get; set; }
        public bool POUR_CONDITION { get; set; }
        public bool POUR_RESULT { get; set; }
        public Nullable<System.DateTime> POUR_CONTENT_UPDATE_DATE { get; set; }
        public System.DateTime STATUS_UPDATE_DATE { get; set; }
    
        public virtual DC_INDEX_INFO DC_INDEX_INFO { get; set; }
    }
}
