//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_WORKLOG_INFO
    {
        public int SID { get; set; }
        public int ORDER_SID { get; set; }
        public int USER_SID { get; set; }
        public string EVENT_KEY { get; set; }
        public System.DateTime EVENT_START_DATE { get; set; }
        public Nullable<System.DateTime> EVENT_END_DATE { get; set; }
    
        public virtual OM_ORDER_INFO OM_ORDER_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
    }
}
