//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_BLUE_LINK_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LK_BLUE_LINK_ITEM()
        {
            this.LK_BLUE_LINK_DISCONNECT_STATUS = new HashSet<LK_BLUE_LINK_DISCONNECT_STATUS>();
            this.LK_BLUE_LINK_PATTERN = new HashSet<LK_BLUE_LINK_PATTERN>();
            this.LK_BLUE_LINK_RELATION_ENTRY = new HashSet<LK_BLUE_LINK_RELATION_ENTRY>();
            this.LK_BLUE_LINK_RELATION_PUBLISH = new HashSet<LK_BLUE_LINK_RELATION_PUBLISH>();
            this.LK_BLUE_LINK_SUBSCRIBE = new HashSet<LK_BLUE_LINK_SUBSCRIBE>();
        }
    
        public int SID { get; set; }
        public int COMPANY_SID { get; set; }
        public string LABEL { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_DISCONNECT_STATUS> LK_BLUE_LINK_DISCONNECT_STATUS { get; set; }
        public virtual OM_COMPANY_INFO OM_COMPANY_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_PATTERN> LK_BLUE_LINK_PATTERN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_RELATION_ENTRY> LK_BLUE_LINK_RELATION_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_RELATION_PUBLISH> LK_BLUE_LINK_RELATION_PUBLISH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_SUBSCRIBE> LK_BLUE_LINK_SUBSCRIBE { get; set; }
    }
}
