//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_ORANGE_LINK_SUBSCRIBE
    {
        public int SID { get; set; }
        public int INDEX_SID { get; set; }
        public int LINK_SID { get; set; }
        public long TRACKING_ID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int DISCONNECT_STATUS_SID { get; set; }
    
        public virtual DC_INDEX_INFO DC_INDEX_INFO { get; set; }
        public virtual LK_ORANGE_LINK_DISCONNECT_STAT LK_ORANGE_LINK_DISCONNECT_STAT { get; set; }
        public virtual LK_ORANGE_LINK_ITEM LK_ORANGE_LINK_ITEM { get; set; }
    }
}
