//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_RED_LINK_BRANCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LK_RED_LINK_BRANCH()
        {
            this.LK_RED_LINK_PATTERN = new HashSet<LK_RED_LINK_PATTERN>();
        }
    
        public int SID { get; set; }
        public int TARGET_SID { get; set; }
        public string BRANCH_NAME { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        public virtual LK_RED_LINK_TARGET_INDEX LK_RED_LINK_TARGET_INDEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_PATTERN> LK_RED_LINK_PATTERN { get; set; }
    }
}
