//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_RED_LINK_RELATION_ENTRY
    {
        public int SID { get; set; }
        public int RELATION_SID { get; set; }
        public int PATTERN_SID { get; set; }
        public int DISPLAY_ORDER { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        public virtual LK_RED_LINK_PATTERN LK_RED_LINK_PATTERN { get; set; }
        public virtual LK_RED_LINK_RELATION LK_RED_LINK_RELATION { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
    }
}
