//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LK_RED_LINK_SOURCE_ENTRY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LK_RED_LINK_SOURCE_ENTRY()
        {
            this.LK_RED_LINK_SOURCE_IMAGE_INFO = new HashSet<LK_RED_LINK_SOURCE_IMAGE_INFO>();
        }
    
        public int SID { get; set; }
        public int PERIOD_SID { get; set; }
        public int REFERENCE_INDEX_SID { get; set; }
        public int REVISION { get; set; }
        public long TRACKING_ID { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        public virtual DC_INDEX_INFO DC_INDEX_INFO { get; set; }
        public virtual LK_RED_LINK_PERIOD LK_RED_LINK_PERIOD { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_SOURCE_IMAGE_INFO> LK_RED_LINK_SOURCE_IMAGE_INFO { get; set; }
    }
}
