//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NexEntities : DbContext
    {
        public NexEntities()
            : base("name=NexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DC_COLOR_INFO> DC_COLOR_INFO { get; set; }
        public virtual DbSet<DC_DOCUMENT_DATA> DC_DOCUMENT_DATA { get; set; }
        public virtual DbSet<DC_DOCUMENT_HISTORY> DC_DOCUMENT_HISTORY { get; set; }
        public virtual DbSet<DC_DOCUMENT_HISTORY_COPY_DATA> DC_DOCUMENT_HISTORY_COPY_DATA { get; set; }
        public virtual DbSet<DC_DOCUMENT_HISTORY_COPY_INFO> DC_DOCUMENT_HISTORY_COPY_INFO { get; set; }
        public virtual DbSet<DC_FONT_INFO> DC_FONT_INFO { get; set; }
        public virtual DbSet<DC_IMAGE_DATA> DC_IMAGE_DATA { get; set; }
        public virtual DbSet<DC_IMAGE_INFO> DC_IMAGE_INFO { get; set; }
        public virtual DbSet<DC_INDEX_ADDITIONAL_INFO> DC_INDEX_ADDITIONAL_INFO { get; set; }
        public virtual DbSet<DC_INDEX_ADDITIONAL_PRINT_INFO> DC_INDEX_ADDITIONAL_PRINT_INFO { get; set; }
        public virtual DbSet<DC_INDEX_COLOR_INFO> DC_INDEX_COLOR_INFO { get; set; }
        public virtual DbSet<DC_INDEX_INFO> DC_INDEX_INFO { get; set; }
        public virtual DbSet<DC_INDEX_STYLE> DC_INDEX_STYLE { get; set; }
        public virtual DbSet<DC_INDEX_SYN_SETTING> DC_INDEX_SYN_SETTING { get; set; }
        public virtual DbSet<DC_POINT_MARK> DC_POINT_MARK { get; set; }
        public virtual DbSet<DC_PRINT_INFO_BG_IMAGE_DATA> DC_PRINT_INFO_BG_IMAGE_DATA { get; set; }
        public virtual DbSet<DC_PRINT_INFO_BG_IMAGE_INFO> DC_PRINT_INFO_BG_IMAGE_INFO { get; set; }
        public virtual DbSet<DC_PRINT_INFO_BG_SETTING> DC_PRINT_INFO_BG_SETTING { get; set; }
        public virtual DbSet<DC_PRINT_INFO_DETAIL> DC_PRINT_INFO_DETAIL { get; set; }
        public virtual DbSet<DC_PRINT_INFO_HEAD> DC_PRINT_INFO_HEAD { get; set; }
        public virtual DbSet<DC_PRINT_INFO_INDEX_SETTING> DC_PRINT_INFO_INDEX_SETTING { get; set; }
        public virtual DbSet<DC_PRINT_INFO_PAGE_BG_SETTING> DC_PRINT_INFO_PAGE_BG_SETTING { get; set; }
        public virtual DbSet<DC_PRINT_INFO_PAGE_NUM_SETTING> DC_PRINT_INFO_PAGE_NUM_SETTING { get; set; }
        public virtual DbSet<DC_SEARCH_CHARACTER> DC_SEARCH_CHARACTER { get; set; }
        public virtual DbSet<DC_STYLE_INFO> DC_STYLE_INFO { get; set; }
        public virtual DbSet<DC_SUBMIT_FILE_DATA> DC_SUBMIT_FILE_DATA { get; set; }
        public virtual DbSet<DC_SUBMIT_FILE_INFO> DC_SUBMIT_FILE_INFO { get; set; }
        public virtual DbSet<DC_SUBMIT_FILE_INIT_SETTING> DC_SUBMIT_FILE_INIT_SETTING { get; set; }
        public virtual DbSet<DC_SUBMIT_FILECHECK_RESULT> DC_SUBMIT_FILECHECK_RESULT { get; set; }
        public virtual DbSet<FWD_AUDIT_SCHEDULE> FWD_AUDIT_SCHEDULE { get; set; }
        public virtual DbSet<FWD_BUSINESS_CALENDER> FWD_BUSINESS_CALENDER { get; set; }
        public virtual DbSet<FWD_BUSINESS_CALENDER_MSG> FWD_BUSINESS_CALENDER_MSG { get; set; }
        public virtual DbSet<FWD_ERROR_INFO> FWD_ERROR_INFO { get; set; }
        public virtual DbSet<FWD_FINANCIAL_STATUS> FWD_FINANCIAL_STATUS { get; set; }
        public virtual DbSet<FWD_KANRYU_DATA> FWD_KANRYU_DATA { get; set; }
        public virtual DbSet<FWD_KANRYU_FUND_INFO> FWD_KANRYU_FUND_INFO { get; set; }
        public virtual DbSet<FWD_KANRYU_SCHEDULE> FWD_KANRYU_SCHEDULE { get; set; }
        public virtual DbSet<FWD_REPORT_SCHEDULE> FWD_REPORT_SCHEDULE { get; set; }
        public virtual DbSet<FWD_RINPOU_STATUS> FWD_RINPOU_STATUS { get; set; }
        public virtual DbSet<FWD_SCHEDULE_STATUS> FWD_SCHEDULE_STATUS { get; set; }
        public virtual DbSet<FWD_STP_DATA> FWD_STP_DATA { get; set; }
        public virtual DbSet<FWD_STP_SNAPSHOT> FWD_STP_SNAPSHOT { get; set; }
        public virtual DbSet<FWD_SUBMIT_DATA> FWD_SUBMIT_DATA { get; set; }
        public virtual DbSet<FWD_SUBMIT_INFO> FWD_SUBMIT_INFO { get; set; }
        public virtual DbSet<GA_USER_INFO> GA_USER_INFO { get; set; }
        public virtual DbSet<GA_USER_PASSWORD> GA_USER_PASSWORD { get; set; }
        public virtual DbSet<GA_USER_ROLE_INFO> GA_USER_ROLE_INFO { get; set; }
        public virtual DbSet<ID_GRAPH_INFO> ID_GRAPH_INFO { get; set; }
        public virtual DbSet<ID_INDESIGN_BGPOUR_QUEUE> ID_INDESIGN_BGPOUR_QUEUE { get; set; }
        public virtual DbSet<ID_INDESIGN_COLOR_INFO> ID_INDESIGN_COLOR_INFO { get; set; }
        public virtual DbSet<ID_INDESIGN_FILE> ID_INDESIGN_FILE { get; set; }
        public virtual DbSet<ID_INDESIGN_FILE_DATA> ID_INDESIGN_FILE_DATA { get; set; }
        public virtual DbSet<ID_INDESIGN_FONT_INFO> ID_INDESIGN_FONT_INFO { get; set; }
        public virtual DbSet<ID_INDESIGN_IMG> ID_INDESIGN_IMG { get; set; }
        public virtual DbSet<ID_INDESIGN_IMG_DATA> ID_INDESIGN_IMG_DATA { get; set; }
        public virtual DbSet<ID_INDESIGN_PDF_DATA> ID_INDESIGN_PDF_DATA { get; set; }
        public virtual DbSet<ID_INDESIGN_REFLECT_STAT> ID_INDESIGN_REFLECT_STAT { get; set; }
        public virtual DbSet<ID_LABEL_PAGE> ID_LABEL_PAGE { get; set; }
        public virtual DbSet<ID_PAGE_INFO> ID_PAGE_INFO { get; set; }
        public virtual DbSet<ID_PARTS_IMAGE_SETTING> ID_PARTS_IMAGE_SETTING { get; set; }
        public virtual DbSet<ID_PERFORMANCE_DATA> ID_PERFORMANCE_DATA { get; set; }
        public virtual DbSet<ID_PERFORMANCE_QUEUE> ID_PERFORMANCE_QUEUE { get; set; }
        public virtual DbSet<ID_SCHEDULE_DATA> ID_SCHEDULE_DATA { get; set; }
        public virtual DbSet<ID_WORKLOG_INFO> ID_WORKLOG_INFO { get; set; }
        public virtual DbSet<LK_APPLICABLE_DATE> LK_APPLICABLE_DATE { get; set; }
        public virtual DbSet<LK_APPLICABLE_DATE_PUBLISH> LK_APPLICABLE_DATE_PUBLISH { get; set; }
        public virtual DbSet<LK_BLUE_LINK_DISCONNECT_STATUS> LK_BLUE_LINK_DISCONNECT_STATUS { get; set; }
        public virtual DbSet<LK_BLUE_LINK_DURATION> LK_BLUE_LINK_DURATION { get; set; }
        public virtual DbSet<LK_BLUE_LINK_DURATION_ENTRY> LK_BLUE_LINK_DURATION_ENTRY { get; set; }
        public virtual DbSet<LK_BLUE_LINK_DURATION_PUBLISH> LK_BLUE_LINK_DURATION_PUBLISH { get; set; }
        public virtual DbSet<LK_BLUE_LINK_ITEM> LK_BLUE_LINK_ITEM { get; set; }
        public virtual DbSet<LK_BLUE_LINK_PATTERN> LK_BLUE_LINK_PATTERN { get; set; }
        public virtual DbSet<LK_BLUE_LINK_RELATION_ENTRY> LK_BLUE_LINK_RELATION_ENTRY { get; set; }
        public virtual DbSet<LK_BLUE_LINK_RELATION_PUBLISH> LK_BLUE_LINK_RELATION_PUBLISH { get; set; }
        public virtual DbSet<LK_BLUE_LINK_SOURCE_ENTRY> LK_BLUE_LINK_SOURCE_ENTRY { get; set; }
        public virtual DbSet<LK_BLUE_LINK_SOURCE_PUBLISH> LK_BLUE_LINK_SOURCE_PUBLISH { get; set; }
        public virtual DbSet<LK_BLUE_LINK_SUBSCRIBE> LK_BLUE_LINK_SUBSCRIBE { get; set; }
        public virtual DbSet<LK_ORANGE_LINK_DISCONNECT_STAT> LK_ORANGE_LINK_DISCONNECT_STAT { get; set; }
        public virtual DbSet<LK_ORANGE_LINK_ITEM> LK_ORANGE_LINK_ITEM { get; set; }
        public virtual DbSet<LK_ORANGE_LINK_SOURCE_ENTRY> LK_ORANGE_LINK_SOURCE_ENTRY { get; set; }
        public virtual DbSet<LK_ORANGE_LINK_SOURCE_PUBLISH> LK_ORANGE_LINK_SOURCE_PUBLISH { get; set; }
        public virtual DbSet<LK_ORANGE_LINK_SUBSCRIBE> LK_ORANGE_LINK_SUBSCRIBE { get; set; }
        public virtual DbSet<LK_RED_LINK_BRANCH> LK_RED_LINK_BRANCH { get; set; }
        public virtual DbSet<LK_RED_LINK_PATTERN> LK_RED_LINK_PATTERN { get; set; }
        public virtual DbSet<LK_RED_LINK_PERIOD> LK_RED_LINK_PERIOD { get; set; }
        public virtual DbSet<LK_RED_LINK_PERIOD_ENTRY> LK_RED_LINK_PERIOD_ENTRY { get; set; }
        public virtual DbSet<LK_RED_LINK_PERIOD_PUBLISH> LK_RED_LINK_PERIOD_PUBLISH { get; set; }
        public virtual DbSet<LK_RED_LINK_RELATION> LK_RED_LINK_RELATION { get; set; }
        public virtual DbSet<LK_RED_LINK_RELATION_ENTRY> LK_RED_LINK_RELATION_ENTRY { get; set; }
        public virtual DbSet<LK_RED_LINK_SOURCE_ENTRY> LK_RED_LINK_SOURCE_ENTRY { get; set; }
        public virtual DbSet<LK_RED_LINK_SOURCE_IMAGE_INFO> LK_RED_LINK_SOURCE_IMAGE_INFO { get; set; }
        public virtual DbSet<LK_RED_LINK_SOURCE_PUBLISH> LK_RED_LINK_SOURCE_PUBLISH { get; set; }
        public virtual DbSet<LK_RED_LINK_SUBSCRIBE> LK_RED_LINK_SUBSCRIBE { get; set; }
        public virtual DbSet<LK_RED_LINK_TARGET_INDEX> LK_RED_LINK_TARGET_INDEX { get; set; }
        public virtual DbSet<OM_ACCESS_GROUP_INFO> OM_ACCESS_GROUP_INFO { get; set; }
        public virtual DbSet<OM_ACCESS_GROUP_MASTER> OM_ACCESS_GROUP_MASTER { get; set; }
        public virtual DbSet<OM_AGREEMENT_RELATION> OM_AGREEMENT_RELATION { get; set; }
        public virtual DbSet<OM_APPROVAL_INFO> OM_APPROVAL_INFO { get; set; }
        public virtual DbSet<OM_ATTACH_DOC_FILE_DATA> OM_ATTACH_DOC_FILE_DATA { get; set; }
        public virtual DbSet<OM_ATTACH_DOC_FILE_INFO> OM_ATTACH_DOC_FILE_INFO { get; set; }
        public virtual DbSet<OM_ATTACH_DOC_INFO> OM_ATTACH_DOC_INFO { get; set; }
        public virtual DbSet<OM_ATTACH_DOC_REVISION_INFO> OM_ATTACH_DOC_REVISION_INFO { get; set; }
        public virtual DbSet<OM_ATTACH_DOC_SHINKYUU_DATA> OM_ATTACH_DOC_SHINKYUU_DATA { get; set; }
        public virtual DbSet<OM_ATTACH_DOC_SHINKYUU_INFO> OM_ATTACH_DOC_SHINKYUU_INFO { get; set; }
        public virtual DbSet<OM_AUTO_GRP_JOB_REF> OM_AUTO_GRP_JOB_REF { get; set; }
        public virtual DbSet<OM_AUTO_GRP_MST> OM_AUTO_GRP_MST { get; set; }
        public virtual DbSet<OM_CHARGE_COMPANY_INFO> OM_CHARGE_COMPANY_INFO { get; set; }
        public virtual DbSet<OM_COMPANY_ADDITIONAL_INFO> OM_COMPANY_ADDITIONAL_INFO { get; set; }
        public virtual DbSet<OM_COMPANY_INFO> OM_COMPANY_INFO { get; set; }
        public virtual DbSet<OM_CUST_GRP_JOB_REF> OM_CUST_GRP_JOB_REF { get; set; }
        public virtual DbSet<OM_CUST_GRP_MST> OM_CUST_GRP_MST { get; set; }
        public virtual DbSet<OM_DOC_COMMENT> OM_DOC_COMMENT { get; set; }
        public virtual DbSet<OM_DOCUMENT_ACCESS_INFO> OM_DOCUMENT_ACCESS_INFO { get; set; }
        public virtual DbSet<OM_DOCUMENT_BASE_DATA> OM_DOCUMENT_BASE_DATA { get; set; }
        public virtual DbSet<OM_DOCUMENT_BASE_INFO> OM_DOCUMENT_BASE_INFO { get; set; }
        public virtual DbSet<OM_DOCUMENT_CHECKOUT> OM_DOCUMENT_CHECKOUT { get; set; }
        public virtual DbSet<OM_DOCUMENT_INFO> OM_DOCUMENT_INFO { get; set; }
        public virtual DbSet<OM_ERRATUM_FILE_DATA> OM_ERRATUM_FILE_DATA { get; set; }
        public virtual DbSet<OM_ERRATUM_FILE_INFO> OM_ERRATUM_FILE_INFO { get; set; }
        public virtual DbSet<OM_FINANCIAL_SCHEDULE_INFO> OM_FINANCIAL_SCHEDULE_INFO { get; set; }
        public virtual DbSet<OM_FONT_INFO_MASTER> OM_FONT_INFO_MASTER { get; set; }
        public virtual DbSet<OM_FUND_INFO> OM_FUND_INFO { get; set; }
        public virtual DbSet<OM_GENERAL_AUTHORITY_INFO> OM_GENERAL_AUTHORITY_INFO { get; set; }
        public virtual DbSet<OM_INSIDER_GROUP> OM_INSIDER_GROUP { get; set; }
        public virtual DbSet<OM_INSIDER_GROUP_DOC_FORM_MAP> OM_INSIDER_GROUP_DOC_FORM_MAP { get; set; }
        public virtual DbSet<OM_JOB_FORM_INFO> OM_JOB_FORM_INFO { get; set; }
        public virtual DbSet<OM_JOB_INFO> OM_JOB_INFO { get; set; }
        public virtual DbSet<OM_MARKING_ITEM_LIST> OM_MARKING_ITEM_LIST { get; set; }
        public virtual DbSet<OM_MESSAGE_DATA> OM_MESSAGE_DATA { get; set; }
        public virtual DbSet<OM_MESSAGE_INFO> OM_MESSAGE_INFO { get; set; }
        public virtual DbSet<OM_MST_GRP_FUND_REF> OM_MST_GRP_FUND_REF { get; set; }
        public virtual DbSet<OM_MST_GRP_MST> OM_MST_GRP_MST { get; set; }
        public virtual DbSet<OM_OPTION_CONTRACT_INFO> OM_OPTION_CONTRACT_INFO { get; set; }
        public virtual DbSet<OM_ORDER_ACCESS_HISTORY_INFO> OM_ORDER_ACCESS_HISTORY_INFO { get; set; }
        public virtual DbSet<OM_ORDER_ACCESS_INFO> OM_ORDER_ACCESS_INFO { get; set; }
        public virtual DbSet<OM_ORDER_ACCESS_INIT_SETTING> OM_ORDER_ACCESS_INIT_SETTING { get; set; }
        public virtual DbSet<OM_ORDER_ACCESS_USER_INFO> OM_ORDER_ACCESS_USER_INFO { get; set; }
        public virtual DbSet<OM_ORDER_ADDITIONAL_INFO> OM_ORDER_ADDITIONAL_INFO { get; set; }
        public virtual DbSet<OM_ORDER_ATTACH_INFO> OM_ORDER_ATTACH_INFO { get; set; }
        public virtual DbSet<OM_ORDER_GROUP> OM_ORDER_GROUP { get; set; }
        public virtual DbSet<OM_ORDER_INFO> OM_ORDER_INFO { get; set; }
        public virtual DbSet<OM_PDF_FILE_COUPLING> OM_PDF_FILE_COUPLING { get; set; }
        public virtual DbSet<OM_PDF_INDEX_MODEL> OM_PDF_INDEX_MODEL { get; set; }
        public virtual DbSet<OM_PDF_INFO> OM_PDF_INFO { get; set; }
        public virtual DbSet<OM_PDF_OUTPUT_PATTERN_SETTING> OM_PDF_OUTPUT_PATTERN_SETTING { get; set; }
        public virtual DbSet<OM_PDF_PAGE_SETTING> OM_PDF_PAGE_SETTING { get; set; }
        public virtual DbSet<OM_README_DATA> OM_README_DATA { get; set; }
        public virtual DbSet<OM_README_INFO> OM_README_INFO { get; set; }
        public virtual DbSet<OM_RELATION_FUND> OM_RELATION_FUND { get; set; }
        public virtual DbSet<OM_RELATION_ORDER> OM_RELATION_ORDER { get; set; }
        public virtual DbSet<OM_REV_ORG_MAPPING> OM_REV_ORG_MAPPING { get; set; }
        public virtual DbSet<OM_REVISION_INFO> OM_REVISION_INFO { get; set; }
        public virtual DbSet<OM_ROLE_INFO> OM_ROLE_INFO { get; set; }
        public virtual DbSet<OM_SCENARIO_CHANGE_LOG> OM_SCENARIO_CHANGE_LOG { get; set; }
        public virtual DbSet<OM_SELECT_GRP_AND_JOB> OM_SELECT_GRP_AND_JOB { get; set; }
        public virtual DbSet<OM_TEISEI_OPTION_INFO> OM_TEISEI_OPTION_INFO { get; set; }
        public virtual DbSet<OM_USER_INFO> OM_USER_INFO { get; set; }
        public virtual DbSet<OM_USER_LOGIN_INFO> OM_USER_LOGIN_INFO { get; set; }
        public virtual DbSet<OM_USER_OPTION_INFO> OM_USER_OPTION_INFO { get; set; }
        public virtual DbSet<OM_USER_PASSWORD> OM_USER_PASSWORD { get; set; }
        public virtual DbSet<SCHEMAVERSIONS> SCHEMAVERSIONS { get; set; }
        public virtual DbSet<XB_BASIC_INFO> XB_BASIC_INFO { get; set; }
        public virtual DbSet<XB_CONTEXT> XB_CONTEXT { get; set; }
        public virtual DbSet<XB_ENTITY> XB_ENTITY { get; set; }
        public virtual DbSet<XB_EXPLICIT_MEMBER> XB_EXPLICIT_MEMBER { get; set; }
        public virtual DbSet<XB_FOOTNOTE> XB_FOOTNOTE { get; set; }
        public virtual DbSet<XB_FOOTNOTE_STR_ITEM> XB_FOOTNOTE_STR_ITEM { get; set; }
        public virtual DbSet<XB_FS_INFO> XB_FS_INFO { get; set; }
        public virtual DbSet<XB_MEDURE> XB_MEDURE { get; set; }
        public virtual DbSet<XB_PERIOD> XB_PERIOD { get; set; }
        public virtual DbSet<XB_PTRN_REF> XB_PTRN_REF { get; set; }
        public virtual DbSet<XB_SCENARIO> XB_SCENARIO { get; set; }
        public virtual DbSet<XB_SERIES_FS_INFO> XB_SERIES_FS_INFO { get; set; }
        public virtual DbSet<XB_STR_ITEM> XB_STR_ITEM { get; set; }
        public virtual DbSet<XB_STR_ITEM_EXPLICIT_MEMBER> XB_STR_ITEM_EXPLICIT_MEMBER { get; set; }
        public virtual DbSet<XB_TAXONOMY_DATA> XB_TAXONOMY_DATA { get; set; }
        public virtual DbSet<XB_UNIT> XB_UNIT { get; set; }
        public virtual DbSet<XB_UNIT_DENOMINATOR_MEDURE> XB_UNIT_DENOMINATOR_MEDURE { get; set; }
        public virtual DbSet<XB_UNIT_ELEMENT_TYPE> XB_UNIT_ELEMENT_TYPE { get; set; }
        public virtual DbSet<XB_UNIT_NUMERATOR_MEDURE> XB_UNIT_NUMERATOR_MEDURE { get; set; }
        public virtual DbSet<USER_ACCESS_INFO> USER_ACCESS_INFO { get; set; }
    }
}
