//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_FINANCIAL_SCHEDULE_INFO
    {
        public int SID { get; set; }
        public int ORDER_GROUP_SID { get; set; }
        public bool SCHEDULE_TYPE { get; set; }
        public Nullable<System.DateTime> CREATE_BASE_DATE { get; set; }
        public Nullable<System.DateTime> INTERNAL_SUBMIT_DATE { get; set; }
        public Nullable<System.DateTime> FIRST_PROOF_DATE { get; set; }
        public Nullable<System.DateTime> SEND_DRAFT_TO_AUDITOR_DATE { get; set; }
        public Nullable<System.DateTime> FUND_EXAMINATION_DATE { get; set; }
        public Nullable<System.DateTime> AUDIT_COMPLETE_DATE { get; set; }
        public Nullable<System.DateTime> DATA_PROOFREADING_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public byte[] USER_EVENT_VALUE { get; set; }
    
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_ORDER_GROUP OM_ORDER_GROUP { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
    }
}
