//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_MST_GRP_FUND_REF
    {
        public int SID { get; set; }
        public int MST_GRP_SID { get; set; }
        public int SELECT_FUND_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
    
        public virtual OM_FUND_INFO OM_FUND_INFO { get; set; }
        public virtual OM_MST_GRP_MST OM_MST_GRP_MST { get; set; }
    }
}
