//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_MESSAGE_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OM_MESSAGE_INFO()
        {
            this.OM_MESSAGE_DATA = new HashSet<OM_MESSAGE_DATA>();
        }
    
        public int SID { get; set; }
        public bool MESSAGE_TYPE { get; set; }
        public string TITLE { get; set; }
        public string FILE_NAME { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_MESSAGE_DATA> OM_MESSAGE_DATA { get; set; }
    }
}
