//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_OPTION_CONTRACT_INFO
    {
        public int SID { get; set; }
        public int COMPANY_ID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public Nullable<int> TYPE_FLAG { get; set; }
        public byte[] BASIC_DATA_VALUE { get; set; }
        public bool WEB_IMAGE_FLAG { get; set; }
        public bool XML_OUTPUT_FLAG { get; set; }
        public bool SEIMOKU_PDF_FLAG { get; set; }
        public bool ATTACH_DOC_FLAG { get; set; }
        public bool YAKKAN_SHARE_FLAG { get; set; }
        public bool KOUFU_HP_PDF_FLAG { get; set; }
        public bool WEB_LINEARIZE { get; set; }
        public bool FAIMSWD_FLAG { get; set; }
        public bool INTEGRATION_REPORT_FLAG { get; set; }
        public bool TEISEI_SUBMIT_FILE_FLAG { get; set; }
        public bool DOCUMENT_TITLE_SETTING_FLAG { get; set; }
        public bool SUBMIT_FILE_NAME_FLAG { get; set; }
        public bool THREE_COLOR_LINK_FLAG { get; set; }
        public bool TEXT_SEARCH_FLAG { get; set; }
    
        public virtual OM_COMPANY_INFO OM_COMPANY_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
    }
}
