//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_PDF_FILE_COUPLING
    {
        public int SID { get; set; }
        public int PDF_INFO_SID { get; set; }
        public string CONTENTS_TYPE { get; set; }
        public byte DISPLAY_ORDER { get; set; }
        public Nullable<int> PDF_INDEX_MODEL_SID { get; set; }
        public string AUDIT_INSERT_POSITION { get; set; }
        public Nullable<byte> AUDIT_INSERT_POSITION_SEQ { get; set; }
        public string FILE_NAME { get; set; }
        public byte[] FILE_DATA { get; set; }
        public Nullable<System.DateTime> UPLOAD_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public Nullable<int> TODO_AUDIT_DOC_SID { get; set; }
        public Nullable<int> TODO_PAST_ORDER_SID { get; set; }
        public Nullable<int> TODO_RELATION_ORDER_SID { get; set; }
    
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO1 { get; set; }
        public virtual OM_PDF_INFO OM_PDF_INFO { get; set; }
    }
}
