//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ROLE_INFO
    {
        public int SID { get; set; }
        public int USER_SID { get; set; }
        public int ROLE_MASTER_ID { get; set; }
        public bool AVALABLE { get; set; }
        public Nullable<int> INSIDER_GROUP_ID { get; set; }
        public bool IMPORT_AVALABLE { get; set; }
        public bool EXPORT_AVALABLE { get; set; }
        public bool GENERAL_DATA { get; set; }
        public Nullable<System.DateTime> EXPIRE_DATE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
    
        public virtual OM_INSIDER_GROUP OM_INSIDER_GROUP { get; set; }
        public virtual OM_USER_INFO OM_USER_INFO { get; set; }
    }
}
