//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_RELATION_ORDER
    {
        public int SID { get; set; }
        public int ORDER_SID { get; set; }
        public int RELATION_ORDER_SID { get; set; }
        public byte DISPLAY_ORDER { get; set; }
        public bool PAGE_G_HEADER_FLAG { get; set; }
        public bool PAGE_HEADER_FLAG { get; set; }
        public bool PAGE_HONBUN_FLAG { get; set; }
        public bool PAGE_MEMO_FLAG { get; set; }
        public bool PAGE_URA_FLAG { get; set; }
        public bool PAGE_DOC_COMP_FLAG { get; set; }
        public bool PAGE_G_MEMO_FLAG { get; set; }
        public bool PAGE_G_URA_FLAG { get; set; }
        public bool PAGE_G_DOC_COMP_FLAG { get; set; }
    
        public virtual OM_ORDER_INFO OM_ORDER_INFO { get; set; }
        public virtual OM_ORDER_INFO OM_ORDER_INFO1 { get; set; }
    }
}
