//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_SELECT_GRP_AND_JOB
    {
        public int SID { get; set; }
        public int CREATE_USER_SID { get; set; }
        public int SEL_SELECT_JOB_SID { get; set; }
        public byte SELECT_GRP_TYPE { get; set; }
        public Nullable<int> SELECT_GRP_SID { get; set; }
        public Nullable<int> CMP_SELECT_JOB_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
    
        public virtual OM_JOB_INFO OM_JOB_INFO { get; set; }
        public virtual OM_JOB_INFO OM_JOB_INFO1 { get; set; }
    }
}
