//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_TEISEI_OPTION_INFO
    {
        public int SID { get; set; }
        public int ORDER_SID { get; set; }
        public int OLD_ORDER_SID { get; set; }
        public int NEW_ORDER_SID { get; set; }
        public bool MANAGEMENT_EXECTYPE { get; set; }
        public bool FINANCIAL_EXECTYPE { get; set; }
        public bool ITAKU_EXECTYPE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
    
        public virtual OM_ORDER_INFO OM_ORDER_INFO { get; set; }
    }
}
