//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_USER_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OM_USER_INFO()
        {
            this.DC_COLOR_INFO = new HashSet<DC_COLOR_INFO>();
            this.DC_COLOR_INFO1 = new HashSet<DC_COLOR_INFO>();
            this.DC_DOCUMENT_DATA = new HashSet<DC_DOCUMENT_DATA>();
            this.DC_DOCUMENT_DATA1 = new HashSet<DC_DOCUMENT_DATA>();
            this.DC_FONT_INFO = new HashSet<DC_FONT_INFO>();
            this.DC_FONT_INFO1 = new HashSet<DC_FONT_INFO>();
            this.DC_IMAGE_DATA = new HashSet<DC_IMAGE_DATA>();
            this.DC_IMAGE_DATA1 = new HashSet<DC_IMAGE_DATA>();
            this.DC_IMAGE_INFO = new HashSet<DC_IMAGE_INFO>();
            this.DC_IMAGE_INFO1 = new HashSet<DC_IMAGE_INFO>();
            this.DC_INDEX_ADDITIONAL_PRINT_INFO = new HashSet<DC_INDEX_ADDITIONAL_PRINT_INFO>();
            this.DC_INDEX_ADDITIONAL_PRINT_INFO1 = new HashSet<DC_INDEX_ADDITIONAL_PRINT_INFO>();
            this.DC_INDEX_COLOR_INFO = new HashSet<DC_INDEX_COLOR_INFO>();
            this.DC_INDEX_COLOR_INFO1 = new HashSet<DC_INDEX_COLOR_INFO>();
            this.DC_PRINT_INFO_BG_IMAGE_DATA = new HashSet<DC_PRINT_INFO_BG_IMAGE_DATA>();
            this.DC_PRINT_INFO_BG_IMAGE_DATA1 = new HashSet<DC_PRINT_INFO_BG_IMAGE_DATA>();
            this.DC_PRINT_INFO_BG_IMAGE_INFO = new HashSet<DC_PRINT_INFO_BG_IMAGE_INFO>();
            this.DC_PRINT_INFO_BG_IMAGE_INFO1 = new HashSet<DC_PRINT_INFO_BG_IMAGE_INFO>();
            this.DC_PRINT_INFO_BG_SETTING = new HashSet<DC_PRINT_INFO_BG_SETTING>();
            this.DC_PRINT_INFO_BG_SETTING1 = new HashSet<DC_PRINT_INFO_BG_SETTING>();
            this.DC_PRINT_INFO_DETAIL = new HashSet<DC_PRINT_INFO_DETAIL>();
            this.DC_PRINT_INFO_DETAIL1 = new HashSet<DC_PRINT_INFO_DETAIL>();
            this.DC_PRINT_INFO_HEAD = new HashSet<DC_PRINT_INFO_HEAD>();
            this.DC_PRINT_INFO_HEAD1 = new HashSet<DC_PRINT_INFO_HEAD>();
            this.DC_PRINT_INFO_INDEX_SETTING = new HashSet<DC_PRINT_INFO_INDEX_SETTING>();
            this.DC_PRINT_INFO_INDEX_SETTING1 = new HashSet<DC_PRINT_INFO_INDEX_SETTING>();
            this.DC_PRINT_INFO_PAGE_BG_SETTING = new HashSet<DC_PRINT_INFO_PAGE_BG_SETTING>();
            this.DC_PRINT_INFO_PAGE_BG_SETTING1 = new HashSet<DC_PRINT_INFO_PAGE_BG_SETTING>();
            this.DC_PRINT_INFO_PAGE_NUM_SETTING = new HashSet<DC_PRINT_INFO_PAGE_NUM_SETTING>();
            this.DC_PRINT_INFO_PAGE_NUM_SETTING1 = new HashSet<DC_PRINT_INFO_PAGE_NUM_SETTING>();
            this.DC_SEARCH_CHARACTER = new HashSet<DC_SEARCH_CHARACTER>();
            this.DC_SEARCH_CHARACTER1 = new HashSet<DC_SEARCH_CHARACTER>();
            this.DC_SUBMIT_FILE_INFO = new HashSet<DC_SUBMIT_FILE_INFO>();
            this.DC_SUBMIT_FILECHECK_RESULT = new HashSet<DC_SUBMIT_FILECHECK_RESULT>();
            this.FL_ADMIN_USER_INFO = new HashSet<FL_ADMIN_USER_INFO>();
            this.FL_MAIL_INFO_CC = new HashSet<FL_MAIL_INFO_CC>();
            this.FWD_BUSINESS_CALENDER = new HashSet<FWD_BUSINESS_CALENDER>();
            this.FWD_BUSINESS_CALENDER1 = new HashSet<FWD_BUSINESS_CALENDER>();
            this.FWD_BUSINESS_CALENDER_MSG = new HashSet<FWD_BUSINESS_CALENDER_MSG>();
            this.FWD_BUSINESS_CALENDER_MSG1 = new HashSet<FWD_BUSINESS_CALENDER_MSG>();
            this.ID_WORKLOG_INFO = new HashSet<ID_WORKLOG_INFO>();
            this.LK_APPLICABLE_DATE_PUBLISH = new HashSet<LK_APPLICABLE_DATE_PUBLISH>();
            this.LK_APPLICABLE_DATE_PUBLISH1 = new HashSet<LK_APPLICABLE_DATE_PUBLISH>();
            this.LK_BLUE_LINK_DURATION_ENTRY = new HashSet<LK_BLUE_LINK_DURATION_ENTRY>();
            this.LK_BLUE_LINK_DURATION_ENTRY1 = new HashSet<LK_BLUE_LINK_DURATION_ENTRY>();
            this.LK_BLUE_LINK_DURATION_PUBLISH = new HashSet<LK_BLUE_LINK_DURATION_PUBLISH>();
            this.LK_BLUE_LINK_DURATION_PUBLISH1 = new HashSet<LK_BLUE_LINK_DURATION_PUBLISH>();
            this.LK_BLUE_LINK_PATTERN = new HashSet<LK_BLUE_LINK_PATTERN>();
            this.LK_BLUE_LINK_PATTERN1 = new HashSet<LK_BLUE_LINK_PATTERN>();
            this.LK_BLUE_LINK_RELATION_ENTRY = new HashSet<LK_BLUE_LINK_RELATION_ENTRY>();
            this.LK_BLUE_LINK_RELATION_ENTRY1 = new HashSet<LK_BLUE_LINK_RELATION_ENTRY>();
            this.LK_BLUE_LINK_RELATION_PUBLISH = new HashSet<LK_BLUE_LINK_RELATION_PUBLISH>();
            this.LK_BLUE_LINK_RELATION_PUBLISH1 = new HashSet<LK_BLUE_LINK_RELATION_PUBLISH>();
            this.LK_BLUE_LINK_SOURCE_ENTRY = new HashSet<LK_BLUE_LINK_SOURCE_ENTRY>();
            this.LK_BLUE_LINK_SOURCE_ENTRY1 = new HashSet<LK_BLUE_LINK_SOURCE_ENTRY>();
            this.LK_BLUE_LINK_SOURCE_PUBLISH = new HashSet<LK_BLUE_LINK_SOURCE_PUBLISH>();
            this.LK_BLUE_LINK_SOURCE_PUBLISH1 = new HashSet<LK_BLUE_LINK_SOURCE_PUBLISH>();
            this.LK_ORANGE_LINK_SOURCE_ENTRY = new HashSet<LK_ORANGE_LINK_SOURCE_ENTRY>();
            this.LK_ORANGE_LINK_SOURCE_ENTRY1 = new HashSet<LK_ORANGE_LINK_SOURCE_ENTRY>();
            this.LK_ORANGE_LINK_SOURCE_PUBLISH = new HashSet<LK_ORANGE_LINK_SOURCE_PUBLISH>();
            this.LK_ORANGE_LINK_SOURCE_PUBLISH1 = new HashSet<LK_ORANGE_LINK_SOURCE_PUBLISH>();
            this.LK_RED_LINK_PERIOD_ENTRY = new HashSet<LK_RED_LINK_PERIOD_ENTRY>();
            this.LK_RED_LINK_PERIOD_ENTRY1 = new HashSet<LK_RED_LINK_PERIOD_ENTRY>();
            this.LK_RED_LINK_PERIOD_PUBLISH = new HashSet<LK_RED_LINK_PERIOD_PUBLISH>();
            this.LK_RED_LINK_PERIOD_PUBLISH1 = new HashSet<LK_RED_LINK_PERIOD_PUBLISH>();
            this.LK_RED_LINK_RELATION = new HashSet<LK_RED_LINK_RELATION>();
            this.LK_RED_LINK_RELATION1 = new HashSet<LK_RED_LINK_RELATION>();
            this.LK_RED_LINK_RELATION_ENTRY = new HashSet<LK_RED_LINK_RELATION_ENTRY>();
            this.LK_RED_LINK_RELATION_ENTRY1 = new HashSet<LK_RED_LINK_RELATION_ENTRY>();
            this.LK_RED_LINK_SOURCE_ENTRY = new HashSet<LK_RED_LINK_SOURCE_ENTRY>();
            this.LK_RED_LINK_SOURCE_ENTRY1 = new HashSet<LK_RED_LINK_SOURCE_ENTRY>();
            this.LK_RED_LINK_SOURCE_PUBLISH = new HashSet<LK_RED_LINK_SOURCE_PUBLISH>();
            this.LK_RED_LINK_SOURCE_PUBLISH1 = new HashSet<LK_RED_LINK_SOURCE_PUBLISH>();
            this.OM_ACCESS_GROUP_INFO = new HashSet<OM_ACCESS_GROUP_INFO>();
            this.OM_AGREEMENT_RELATION = new HashSet<OM_AGREEMENT_RELATION>();
            this.OM_AGREEMENT_RELATION1 = new HashSet<OM_AGREEMENT_RELATION>();
            this.OM_APPROVAL_INFO = new HashSet<OM_APPROVAL_INFO>();
            this.OM_APPROVAL_INFO1 = new HashSet<OM_APPROVAL_INFO>();
            this.OM_ATTACH_DOC_FILE_INFO = new HashSet<OM_ATTACH_DOC_FILE_INFO>();
            this.OM_ATTACH_DOC_FILE_INFO1 = new HashSet<OM_ATTACH_DOC_FILE_INFO>();
            this.OM_ATTACH_DOC_INFO = new HashSet<OM_ATTACH_DOC_INFO>();
            this.OM_ATTACH_DOC_REVISION_INFO = new HashSet<OM_ATTACH_DOC_REVISION_INFO>();
            this.OM_ATTACH_DOC_REVISION_INFO1 = new HashSet<OM_ATTACH_DOC_REVISION_INFO>();
            this.OM_ATTACH_DOC_SHINKYUU_INFO = new HashSet<OM_ATTACH_DOC_SHINKYUU_INFO>();
            this.OM_ATTACH_DOC_SHINKYUU_INFO1 = new HashSet<OM_ATTACH_DOC_SHINKYUU_INFO>();
            this.OM_CHARGE_COMPANY_INFO = new HashSet<OM_CHARGE_COMPANY_INFO>();
            this.OM_CUST_GRP_MST = new HashSet<OM_CUST_GRP_MST>();
            this.OM_DOC_COMMENT = new HashSet<OM_DOC_COMMENT>();
            this.OM_DOC_COMMENT1 = new HashSet<OM_DOC_COMMENT>();
            this.OM_DOCUMENT_ACCESS_INFO = new HashSet<OM_DOCUMENT_ACCESS_INFO>();
            this.OM_DOCUMENT_ACCESS_INFO1 = new HashSet<OM_DOCUMENT_ACCESS_INFO>();
            this.OM_DOCUMENT_BASE_DATA = new HashSet<OM_DOCUMENT_BASE_DATA>();
            this.OM_DOCUMENT_BASE_DATA1 = new HashSet<OM_DOCUMENT_BASE_DATA>();
            this.OM_DOCUMENT_BASE_INFO = new HashSet<OM_DOCUMENT_BASE_INFO>();
            this.OM_DOCUMENT_BASE_INFO1 = new HashSet<OM_DOCUMENT_BASE_INFO>();
            this.OM_DOCUMENT_CHECKOUT = new HashSet<OM_DOCUMENT_CHECKOUT>();
            this.OM_DOCUMENT_CHECKOUT1 = new HashSet<OM_DOCUMENT_CHECKOUT>();
            this.OM_DOCUMENT_CHECKOUT2 = new HashSet<OM_DOCUMENT_CHECKOUT>();
            this.OM_DOCUMENT_INFO = new HashSet<OM_DOCUMENT_INFO>();
            this.OM_DOCUMENT_INFO1 = new HashSet<OM_DOCUMENT_INFO>();
            this.OM_DOCUMENT_INFO2 = new HashSet<OM_DOCUMENT_INFO>();
            this.OM_ERRATUM_FILE_DATA = new HashSet<OM_ERRATUM_FILE_DATA>();
            this.OM_ERRATUM_FILE_DATA1 = new HashSet<OM_ERRATUM_FILE_DATA>();
            this.OM_ERRATUM_FILE_INFO = new HashSet<OM_ERRATUM_FILE_INFO>();
            this.OM_ERRATUM_FILE_INFO1 = new HashSet<OM_ERRATUM_FILE_INFO>();
            this.OM_FINANCIAL_SCHEDULE_INFO = new HashSet<OM_FINANCIAL_SCHEDULE_INFO>();
            this.OM_FINANCIAL_SCHEDULE_INFO1 = new HashSet<OM_FINANCIAL_SCHEDULE_INFO>();
            this.OM_FONT_INFO_MASTER = new HashSet<OM_FONT_INFO_MASTER>();
            this.OM_FONT_INFO_MASTER1 = new HashSet<OM_FONT_INFO_MASTER>();
            this.OM_INSIDER_GROUP = new HashSet<OM_INSIDER_GROUP>();
            this.OM_INSIDER_GROUP1 = new HashSet<OM_INSIDER_GROUP>();
            this.OM_INSIDER_GROUP_DOC_FORM_MAP = new HashSet<OM_INSIDER_GROUP_DOC_FORM_MAP>();
            this.OM_INSIDER_GROUP_DOC_FORM_MAP1 = new HashSet<OM_INSIDER_GROUP_DOC_FORM_MAP>();
            this.OM_MARKING_ITEM_LIST = new HashSet<OM_MARKING_ITEM_LIST>();
            this.OM_MARKING_ITEM_LIST1 = new HashSet<OM_MARKING_ITEM_LIST>();
            this.OM_OPTION_CONTRACT_INFO = new HashSet<OM_OPTION_CONTRACT_INFO>();
            this.OM_OPTION_CONTRACT_INFO1 = new HashSet<OM_OPTION_CONTRACT_INFO>();
            this.OM_ORDER_ACCESS_HISTORY_INFO = new HashSet<OM_ORDER_ACCESS_HISTORY_INFO>();
            this.OM_ORDER_ACCESS_HISTORY_INFO1 = new HashSet<OM_ORDER_ACCESS_HISTORY_INFO>();
            this.OM_ORDER_ACCESS_INFO = new HashSet<OM_ORDER_ACCESS_INFO>();
            this.OM_ORDER_ACCESS_INFO1 = new HashSet<OM_ORDER_ACCESS_INFO>();
            this.OM_ORDER_ACCESS_INIT_SETTING = new HashSet<OM_ORDER_ACCESS_INIT_SETTING>();
            this.OM_ORDER_ACCESS_INIT_SETTING1 = new HashSet<OM_ORDER_ACCESS_INIT_SETTING>();
            this.OM_ORDER_ACCESS_USER_INFO = new HashSet<OM_ORDER_ACCESS_USER_INFO>();
            this.OM_ORDER_ACCESS_USER_INFO1 = new HashSet<OM_ORDER_ACCESS_USER_INFO>();
            this.OM_ORDER_ACCESS_USER_INFO2 = new HashSet<OM_ORDER_ACCESS_USER_INFO>();
            this.OM_ORDER_ADDITIONAL_INFO = new HashSet<OM_ORDER_ADDITIONAL_INFO>();
            this.OM_ORDER_ADDITIONAL_INFO1 = new HashSet<OM_ORDER_ADDITIONAL_INFO>();
            this.OM_ORDER_ATTACH_INFO = new HashSet<OM_ORDER_ATTACH_INFO>();
            this.OM_ORDER_ATTACH_INFO1 = new HashSet<OM_ORDER_ATTACH_INFO>();
            this.OM_PDF_FILE_COUPLING = new HashSet<OM_PDF_FILE_COUPLING>();
            this.OM_PDF_FILE_COUPLING1 = new HashSet<OM_PDF_FILE_COUPLING>();
            this.OM_PDF_INDEX_MODEL = new HashSet<OM_PDF_INDEX_MODEL>();
            this.OM_PDF_INDEX_MODEL1 = new HashSet<OM_PDF_INDEX_MODEL>();
            this.OM_PDF_INFO = new HashSet<OM_PDF_INFO>();
            this.OM_PDF_INFO1 = new HashSet<OM_PDF_INFO>();
            this.OM_PDF_OUTPUT_PATTERN_SETTING = new HashSet<OM_PDF_OUTPUT_PATTERN_SETTING>();
            this.OM_PDF_PAGE_SETTING = new HashSet<OM_PDF_PAGE_SETTING>();
            this.OM_PDF_PAGE_SETTING1 = new HashSet<OM_PDF_PAGE_SETTING>();
            this.OM_README_INFO = new HashSet<OM_README_INFO>();
            this.OM_README_INFO1 = new HashSet<OM_README_INFO>();
            this.OM_REV_ORG_MAPPING = new HashSet<OM_REV_ORG_MAPPING>();
            this.OM_REV_ORG_MAPPING1 = new HashSet<OM_REV_ORG_MAPPING>();
            this.OM_REVISION_INFO = new HashSet<OM_REVISION_INFO>();
            this.OM_REVISION_INFO1 = new HashSet<OM_REVISION_INFO>();
            this.OM_ROLE_INFO = new HashSet<OM_ROLE_INFO>();
            this.OM_SCENARIO_CHANGE_LOG = new HashSet<OM_SCENARIO_CHANGE_LOG>();
            this.OM_SCENARIO_CHANGE_LOG1 = new HashSet<OM_SCENARIO_CHANGE_LOG>();
            this.OM_USER_OPTION_INFO = new HashSet<OM_USER_OPTION_INFO>();
            this.OM_USER_PASSWORD = new HashSet<OM_USER_PASSWORD>();
        }
    
        public int SID { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public Nullable<int> COMPANY_SID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_NAME_RB { get; set; }
        public bool INVALIDATED { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int ENTRY_USER_SID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public int UPDATE_USER_SID { get; set; }
        public bool USER_MANAGEMENT_AUTHORITY { get; set; }
        public Nullable<System.DateTime> ACCOUNT_EXPIRE_DATE { get; set; }
        public bool XML_DATA_OUTPUT { get; set; }
        public Nullable<System.DateTime> FALSIFICATION_FIRST_DATETIME { get; set; }
        public Nullable<byte> FALSIFICATION_COUNT { get; set; }
        public Nullable<System.DateTime> FALSIFICATION_OVERED_DATETIME { get; set; }
        public bool ESCAPE_SECURITY_CHECK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_COLOR_INFO> DC_COLOR_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_COLOR_INFO> DC_COLOR_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_DOCUMENT_DATA> DC_DOCUMENT_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_DOCUMENT_DATA> DC_DOCUMENT_DATA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_FONT_INFO> DC_FONT_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_FONT_INFO> DC_FONT_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_IMAGE_DATA> DC_IMAGE_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_IMAGE_DATA> DC_IMAGE_DATA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_IMAGE_INFO> DC_IMAGE_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_IMAGE_INFO> DC_IMAGE_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_INDEX_ADDITIONAL_PRINT_INFO> DC_INDEX_ADDITIONAL_PRINT_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_INDEX_ADDITIONAL_PRINT_INFO> DC_INDEX_ADDITIONAL_PRINT_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_INDEX_COLOR_INFO> DC_INDEX_COLOR_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_INDEX_COLOR_INFO> DC_INDEX_COLOR_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_BG_IMAGE_DATA> DC_PRINT_INFO_BG_IMAGE_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_BG_IMAGE_DATA> DC_PRINT_INFO_BG_IMAGE_DATA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_BG_IMAGE_INFO> DC_PRINT_INFO_BG_IMAGE_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_BG_IMAGE_INFO> DC_PRINT_INFO_BG_IMAGE_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_BG_SETTING> DC_PRINT_INFO_BG_SETTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_BG_SETTING> DC_PRINT_INFO_BG_SETTING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_DETAIL> DC_PRINT_INFO_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_DETAIL> DC_PRINT_INFO_DETAIL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_HEAD> DC_PRINT_INFO_HEAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_HEAD> DC_PRINT_INFO_HEAD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_INDEX_SETTING> DC_PRINT_INFO_INDEX_SETTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_INDEX_SETTING> DC_PRINT_INFO_INDEX_SETTING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_PAGE_BG_SETTING> DC_PRINT_INFO_PAGE_BG_SETTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_PAGE_BG_SETTING> DC_PRINT_INFO_PAGE_BG_SETTING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_PAGE_NUM_SETTING> DC_PRINT_INFO_PAGE_NUM_SETTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_PRINT_INFO_PAGE_NUM_SETTING> DC_PRINT_INFO_PAGE_NUM_SETTING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_SEARCH_CHARACTER> DC_SEARCH_CHARACTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_SEARCH_CHARACTER> DC_SEARCH_CHARACTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_SUBMIT_FILE_INFO> DC_SUBMIT_FILE_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC_SUBMIT_FILECHECK_RESULT> DC_SUBMIT_FILECHECK_RESULT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FL_ADMIN_USER_INFO> FL_ADMIN_USER_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FL_MAIL_INFO_CC> FL_MAIL_INFO_CC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWD_BUSINESS_CALENDER> FWD_BUSINESS_CALENDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWD_BUSINESS_CALENDER> FWD_BUSINESS_CALENDER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWD_BUSINESS_CALENDER_MSG> FWD_BUSINESS_CALENDER_MSG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWD_BUSINESS_CALENDER_MSG> FWD_BUSINESS_CALENDER_MSG1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ID_WORKLOG_INFO> ID_WORKLOG_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_APPLICABLE_DATE_PUBLISH> LK_APPLICABLE_DATE_PUBLISH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_APPLICABLE_DATE_PUBLISH> LK_APPLICABLE_DATE_PUBLISH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_DURATION_ENTRY> LK_BLUE_LINK_DURATION_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_DURATION_ENTRY> LK_BLUE_LINK_DURATION_ENTRY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_DURATION_PUBLISH> LK_BLUE_LINK_DURATION_PUBLISH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_DURATION_PUBLISH> LK_BLUE_LINK_DURATION_PUBLISH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_PATTERN> LK_BLUE_LINK_PATTERN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_PATTERN> LK_BLUE_LINK_PATTERN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_RELATION_ENTRY> LK_BLUE_LINK_RELATION_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_RELATION_ENTRY> LK_BLUE_LINK_RELATION_ENTRY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_RELATION_PUBLISH> LK_BLUE_LINK_RELATION_PUBLISH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_RELATION_PUBLISH> LK_BLUE_LINK_RELATION_PUBLISH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_SOURCE_ENTRY> LK_BLUE_LINK_SOURCE_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_SOURCE_ENTRY> LK_BLUE_LINK_SOURCE_ENTRY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_SOURCE_PUBLISH> LK_BLUE_LINK_SOURCE_PUBLISH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_BLUE_LINK_SOURCE_PUBLISH> LK_BLUE_LINK_SOURCE_PUBLISH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_ORANGE_LINK_SOURCE_ENTRY> LK_ORANGE_LINK_SOURCE_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_ORANGE_LINK_SOURCE_ENTRY> LK_ORANGE_LINK_SOURCE_ENTRY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_ORANGE_LINK_SOURCE_PUBLISH> LK_ORANGE_LINK_SOURCE_PUBLISH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_ORANGE_LINK_SOURCE_PUBLISH> LK_ORANGE_LINK_SOURCE_PUBLISH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_PERIOD_ENTRY> LK_RED_LINK_PERIOD_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_PERIOD_ENTRY> LK_RED_LINK_PERIOD_ENTRY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_PERIOD_PUBLISH> LK_RED_LINK_PERIOD_PUBLISH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_PERIOD_PUBLISH> LK_RED_LINK_PERIOD_PUBLISH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_RELATION> LK_RED_LINK_RELATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_RELATION> LK_RED_LINK_RELATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_RELATION_ENTRY> LK_RED_LINK_RELATION_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_RELATION_ENTRY> LK_RED_LINK_RELATION_ENTRY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_SOURCE_ENTRY> LK_RED_LINK_SOURCE_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_SOURCE_ENTRY> LK_RED_LINK_SOURCE_ENTRY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_SOURCE_PUBLISH> LK_RED_LINK_SOURCE_PUBLISH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LK_RED_LINK_SOURCE_PUBLISH> LK_RED_LINK_SOURCE_PUBLISH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ACCESS_GROUP_INFO> OM_ACCESS_GROUP_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_AGREEMENT_RELATION> OM_AGREEMENT_RELATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_AGREEMENT_RELATION> OM_AGREEMENT_RELATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_APPROVAL_INFO> OM_APPROVAL_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_APPROVAL_INFO> OM_APPROVAL_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ATTACH_DOC_FILE_INFO> OM_ATTACH_DOC_FILE_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ATTACH_DOC_FILE_INFO> OM_ATTACH_DOC_FILE_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ATTACH_DOC_INFO> OM_ATTACH_DOC_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ATTACH_DOC_REVISION_INFO> OM_ATTACH_DOC_REVISION_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ATTACH_DOC_REVISION_INFO> OM_ATTACH_DOC_REVISION_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ATTACH_DOC_SHINKYUU_INFO> OM_ATTACH_DOC_SHINKYUU_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ATTACH_DOC_SHINKYUU_INFO> OM_ATTACH_DOC_SHINKYUU_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_CHARGE_COMPANY_INFO> OM_CHARGE_COMPANY_INFO { get; set; }
        public virtual OM_COMPANY_INFO OM_COMPANY_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_CUST_GRP_MST> OM_CUST_GRP_MST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOC_COMMENT> OM_DOC_COMMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOC_COMMENT> OM_DOC_COMMENT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOCUMENT_ACCESS_INFO> OM_DOCUMENT_ACCESS_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOCUMENT_ACCESS_INFO> OM_DOCUMENT_ACCESS_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOCUMENT_BASE_DATA> OM_DOCUMENT_BASE_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOCUMENT_BASE_DATA> OM_DOCUMENT_BASE_DATA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOCUMENT_BASE_INFO> OM_DOCUMENT_BASE_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOCUMENT_BASE_INFO> OM_DOCUMENT_BASE_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOCUMENT_CHECKOUT> OM_DOCUMENT_CHECKOUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOCUMENT_CHECKOUT> OM_DOCUMENT_CHECKOUT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOCUMENT_CHECKOUT> OM_DOCUMENT_CHECKOUT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOCUMENT_INFO> OM_DOCUMENT_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOCUMENT_INFO> OM_DOCUMENT_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_DOCUMENT_INFO> OM_DOCUMENT_INFO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ERRATUM_FILE_DATA> OM_ERRATUM_FILE_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ERRATUM_FILE_DATA> OM_ERRATUM_FILE_DATA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ERRATUM_FILE_INFO> OM_ERRATUM_FILE_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ERRATUM_FILE_INFO> OM_ERRATUM_FILE_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_FINANCIAL_SCHEDULE_INFO> OM_FINANCIAL_SCHEDULE_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_FINANCIAL_SCHEDULE_INFO> OM_FINANCIAL_SCHEDULE_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_FONT_INFO_MASTER> OM_FONT_INFO_MASTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_FONT_INFO_MASTER> OM_FONT_INFO_MASTER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_INSIDER_GROUP> OM_INSIDER_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_INSIDER_GROUP> OM_INSIDER_GROUP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_INSIDER_GROUP_DOC_FORM_MAP> OM_INSIDER_GROUP_DOC_FORM_MAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_INSIDER_GROUP_DOC_FORM_MAP> OM_INSIDER_GROUP_DOC_FORM_MAP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_MARKING_ITEM_LIST> OM_MARKING_ITEM_LIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_MARKING_ITEM_LIST> OM_MARKING_ITEM_LIST1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_OPTION_CONTRACT_INFO> OM_OPTION_CONTRACT_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_OPTION_CONTRACT_INFO> OM_OPTION_CONTRACT_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ORDER_ACCESS_HISTORY_INFO> OM_ORDER_ACCESS_HISTORY_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ORDER_ACCESS_HISTORY_INFO> OM_ORDER_ACCESS_HISTORY_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ORDER_ACCESS_INFO> OM_ORDER_ACCESS_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ORDER_ACCESS_INFO> OM_ORDER_ACCESS_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ORDER_ACCESS_INIT_SETTING> OM_ORDER_ACCESS_INIT_SETTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ORDER_ACCESS_INIT_SETTING> OM_ORDER_ACCESS_INIT_SETTING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ORDER_ACCESS_USER_INFO> OM_ORDER_ACCESS_USER_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ORDER_ACCESS_USER_INFO> OM_ORDER_ACCESS_USER_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ORDER_ACCESS_USER_INFO> OM_ORDER_ACCESS_USER_INFO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ORDER_ADDITIONAL_INFO> OM_ORDER_ADDITIONAL_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ORDER_ADDITIONAL_INFO> OM_ORDER_ADDITIONAL_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ORDER_ATTACH_INFO> OM_ORDER_ATTACH_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ORDER_ATTACH_INFO> OM_ORDER_ATTACH_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_PDF_FILE_COUPLING> OM_PDF_FILE_COUPLING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_PDF_FILE_COUPLING> OM_PDF_FILE_COUPLING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_PDF_INDEX_MODEL> OM_PDF_INDEX_MODEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_PDF_INDEX_MODEL> OM_PDF_INDEX_MODEL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_PDF_INFO> OM_PDF_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_PDF_INFO> OM_PDF_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_PDF_OUTPUT_PATTERN_SETTING> OM_PDF_OUTPUT_PATTERN_SETTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_PDF_PAGE_SETTING> OM_PDF_PAGE_SETTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_PDF_PAGE_SETTING> OM_PDF_PAGE_SETTING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_README_INFO> OM_README_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_README_INFO> OM_README_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_REV_ORG_MAPPING> OM_REV_ORG_MAPPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_REV_ORG_MAPPING> OM_REV_ORG_MAPPING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_REVISION_INFO> OM_REVISION_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_REVISION_INFO> OM_REVISION_INFO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_ROLE_INFO> OM_ROLE_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_SCENARIO_CHANGE_LOG> OM_SCENARIO_CHANGE_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_SCENARIO_CHANGE_LOG> OM_SCENARIO_CHANGE_LOG1 { get; set; }
        public virtual OM_USER_LOGIN_INFO OM_USER_LOGIN_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_USER_OPTION_INFO> OM_USER_OPTION_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_USER_PASSWORD> OM_USER_PASSWORD { get; set; }
    }
}
