//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class XB_EXPLICIT_MEMBER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XB_EXPLICIT_MEMBER()
        {
            this.XB_STR_ITEM_EXPLICIT_MEMBER = new HashSet<XB_STR_ITEM_EXPLICIT_MEMBER>();
        }
    
        public int SID { get; set; }
        public int BASIC_SID { get; set; }
        public string DIMENTION { get; set; }
        public string MEMBER { get; set; }
    
        public virtual XB_BASIC_INFO XB_BASIC_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XB_STR_ITEM_EXPLICIT_MEMBER> XB_STR_ITEM_EXPLICIT_MEMBER { get; set; }
    }
}
