//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class XB_FS_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XB_FS_INFO()
        {
            this.XB_PTRN_REF = new HashSet<XB_PTRN_REF>();
        }
    
        public int SID { get; set; }
        public int BASIC_SID { get; set; }
        public string REPORT_CODE { get; set; }
        public System.DateTime FISCAL_DATE { get; set; }
        public string CON_INDUSTRY_CODE { get; set; }
        public string NONCON_INDUSTRY_CODE { get; set; }
        public Nullable<byte> CON_ACCOUNT_STANDARD_CODE { get; set; }
        public Nullable<byte> NONCON_ACCOUNT_STANDARD_CODE { get; set; }
        public Nullable<System.DateTime> CON_TAXONOMY_RELEASE_DATE { get; set; }
        public Nullable<System.DateTime> NONCON_TAXONOMY_RELEASE_DATE { get; set; }
        public Nullable<int> CON_MONETARY_ITEM_DECIMALS { get; set; }
        public Nullable<int> NONCON_MONETARY_ITEM_DECIMALS { get; set; }
        public Nullable<int> CON_MONETARY_ITEM_ROUNDING { get; set; }
        public Nullable<int> NONCON_MONETARY_ITEM_ROUNDING { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public short CONSOLIDATION_STATUS { get; set; }
    
        public virtual XB_BASIC_INFO XB_BASIC_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XB_PTRN_REF> XB_PTRN_REF { get; set; }
    }
}
