//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class XB_STR_ITEM_EXPLICIT_MEMBER
    {
        public long SID { get; set; }
        public long STR_ITEM_SID { get; set; }
        public int EXPLICIT_MEMBER_SID { get; set; }
    
        public virtual XB_EXPLICIT_MEMBER XB_EXPLICIT_MEMBER { get; set; }
        public virtual XB_STR_ITEM XB_STR_ITEM { get; set; }
    }
}
