//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class XB_STR_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XB_STR_ITEM()
        {
            this.XB_FOOTNOTE_STR_ITEM = new HashSet<XB_FOOTNOTE_STR_ITEM>();
            this.XB_STR_ITEM_EXPLICIT_MEMBER = new HashSet<XB_STR_ITEM_EXPLICIT_MEMBER>();
        }
    
        public long SID { get; set; }
        public int BASIC_SID { get; set; }
        public int ENTITY_SID { get; set; }
        public int PERIOD_SID { get; set; }
        public Nullable<int> UNIT_SID { get; set; }
        public string ELM_REF { get; set; }
        public string VALUE { get; set; }
        public Nullable<int> DECIMALS { get; set; }
    
        public virtual XB_BASIC_INFO XB_BASIC_INFO { get; set; }
        public virtual XB_ENTITY XB_ENTITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XB_FOOTNOTE_STR_ITEM> XB_FOOTNOTE_STR_ITEM { get; set; }
        public virtual XB_PERIOD XB_PERIOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XB_STR_ITEM_EXPLICIT_MEMBER> XB_STR_ITEM_EXPLICIT_MEMBER { get; set; }
        public virtual XB_UNIT XB_UNIT { get; set; }
    }
}
