//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class XB_TAXONOMY_DATA
    {
        public int SID { get; set; }
        public int BASIC_SID { get; set; }
        public byte[] TAXONOMY_DATA { get; set; }
        public string TYPE { get; set; }
        public string EDINET_SEQ_CODE { get; set; }
    
        public virtual XB_BASIC_INFO XB_BASIC_INFO { get; set; }
    }
}
