//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class XB_UNIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XB_UNIT()
        {
            this.XB_STR_ITEM = new HashSet<XB_STR_ITEM>();
            this.XB_UNIT_DENOMINATOR_MEDURE = new HashSet<XB_UNIT_DENOMINATOR_MEDURE>();
            this.XB_UNIT_ELEMENT_TYPE = new HashSet<XB_UNIT_ELEMENT_TYPE>();
            this.XB_UNIT_NUMERATOR_MEDURE = new HashSet<XB_UNIT_NUMERATOR_MEDURE>();
        }
    
        public int SID { get; set; }
        public int DOC_SID { get; set; }
        public string ID { get; set; }
        public string LABEL { get; set; }
    
        public virtual OM_DOCUMENT_INFO OM_DOCUMENT_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XB_STR_ITEM> XB_STR_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XB_UNIT_DENOMINATOR_MEDURE> XB_UNIT_DENOMINATOR_MEDURE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XB_UNIT_ELEMENT_TYPE> XB_UNIT_ELEMENT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XB_UNIT_NUMERATOR_MEDURE> XB_UNIT_NUMERATOR_MEDURE { get; set; }
    }
}
